export const mockInquiryLimit = {
  akad: 'Teuing',
  authorName: 'Teuing',
  baruPerpanjangan: 'Teuing',
  catatan1: 'Terserah aja',
  commitmentFee: '50000',
  dateLastMoved: 'Teuing',
  datiLokasiProyek: 'Teuing',
  deskripsiResponseFlag: 'Teuing Deskripsi Response',
  frekuensiReview: 'Meh',
  golonganKredit: 'Teuing',
  idLd: 'LD-001',
  infoNomorSPMdanInvoice: 'INV-003',
  inputterName: 'Teuing',
  jenisPenggunaan: 'Teuing',
  keteranganBmpp: 'Kumaha Maneh Wae',
  limitAnak: 'Teuing',
  limitCabangPembukaan: 'Cirebon',
  limitCurrency: 'Rp.',
  limitNominal: '1000000',
  maksimalPenggunaan: '100000',
  mataUangLD: 'Rupiah',
  nilaiDisburse: '300000',
  nilaiKelonggaranTarik: '35000',
  nominalBelumTerpakai: '900000',
  nomorCIF: 'CIF-22233',
  orientasiPenggunaan: 'Teuing',
  pencairanTotal: '30000',
  rate: '30%',
  referensiFloating: 'Teuing',
  responseFlag: 'Teuing',
  revolving: 'Teuing',
  sebelumRestrukturasiPlafon: 'Teuing',
  sifatPiutang: 'Teuing',
  spreadRatePenalty: 'Teuing',
  statusLD: 'Teuing',
  tanggalAP: '23 Aug 2025',
  tanggalBerakhir: '23 Sept 2025',
  tanggalBerlaku: '23 Aug 2025',
  tanggalDisburse: '28 Aug 2025',
  tanggalInputLimmit: '23 Aug 2025',
  tipeRate: 'Teuing',
  totalOutstanding: '10000',
};
