export const MODALPK = {
  DETAIL_FACILITY: 'DETAIL',
  DETAIL_FACILITY_PENGAJUAN_PERIKATAN: 'DETAIL_PENGAJUAN_PERIKATAN',
  DETAIL_FACILITY_PK: 'DETAIL_FACILITY_PK',
  EDIT_RINGKASAN: 'EDIT_RINGKASAN',
  FORM_FACILITY: 'FORM_FACILITY',
  FORM_FACILITY_PENGAJUAN_PERIKATAN: 'FORM_FACILITY_PENGAJUAN_PERIKATAN',
  MODAL_DOCUMENT_PROVISION: 'MODAL_DOCUMENT_PROVISION',
  NEW_PROCESSING_TYPE: 'NEW_PROCESSING_TYPE',
  TABLE_PAYMENT_FACILITY_EXISTING: 'TABLE_PAYMENT_FACILITY_EXISTING',
};
