// tslint:disable
/**
 * OpenAPI Parameter Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoParamVAResponse
 */
export interface BaseResponseGenericSingleDtoParamVAResponse {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoParamVAResponse}
     * @memberof BaseResponseGenericSingleDtoParamVAResponse
     */
    data?: GenericSingleDtoParamVAResponse;
}
/**
 * 
 * @export
 * @interface BaseResponseGetParameterListByModuleResponseDto
 */
export interface BaseResponseGetParameterListByModuleResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GetParameterListByModuleResponseDto}
     * @memberof BaseResponseGetParameterListByModuleResponseDto
     */
    data?: GetParameterListByModuleResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseString
 */
export interface BaseResponseString {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    data?: string;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoParamVAResponse
 */
export interface GenericSingleDtoParamVAResponse {
    /**
     * 
     * @type {ParamVAResponse}
     * @memberof GenericSingleDtoParamVAResponse
     */
    content?: ParamVAResponse;
}
/**
 * 
 * @export
 * @interface GetParameterListByListModuleRequestDto
 */
export interface GetParameterListByListModuleRequestDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetParameterListByListModuleRequestDto
     */
    listModule?: Array<string>;
}
/**
 * 
 * @export
 * @interface GetParameterListByModuleResponseDto
 */
export interface GetParameterListByModuleResponseDto {
    /**
     * 
     * @type {Array<ParameterDto>}
     * @memberof GetParameterListByModuleResponseDto
     */
    listParameter?: Array<ParameterDto>;
}
/**
 * 
 * @export
 * @interface GetParameterListByValueRequestDto
 */
export interface GetParameterListByValueRequestDto {
    /**
     * 
     * @type {string}
     * @memberof GetParameterListByValueRequestDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof GetParameterListByValueRequestDto
     */
    value?: string;
}
/**
 * 
 * @export
 * @interface GetParameterRequestDto
 */
export interface GetParameterRequestDto {
    /**
     * 
     * @type {string}
     * @memberof GetParameterRequestDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof GetParameterRequestDto
     */
    key?: string;
}
/**
 * 
 * @export
 * @interface GetParameterVARequest
 */
export interface GetParameterVARequest {
    /**
     * 
     * @type {string}
     * @memberof GetParameterVARequest
     */
    bankName: string;
    /**
     * 
     * @type {string}
     * @memberof GetParameterVARequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof GetParameterVARequest
     */
    vaType: string;
}
/**
 * 
 * @export
 * @interface ParamVAResponse
 */
export interface ParamVAResponse {
    /**
     * 
     * @type {string}
     * @memberof ParamVAResponse
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof ParamVAResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ParamVAResponse
     */
    vaType?: string;
    /**
     * 
     * @type {string}
     * @memberof ParamVAResponse
     */
    vaTypeDigit?: string;
    /**
     * 
     * @type {string}
     * @memberof ParamVAResponse
     */
    customerType?: string;
    /**
     * 
     * @type {string}
     * @memberof ParamVAResponse
     */
    bankPrefix?: string;
    /**
     * 
     * @type {number}
     * @memberof ParamVAResponse
     */
    totalDigit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ParamVAResponse
     */
    isActive?: boolean;
}
/**
 * 
 * @export
 * @interface ParameterDto
 */
export interface ParameterDto {
    /**
     * 
     * @type {number}
     * @memberof ParameterDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value1?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value2?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value3?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value4?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value5?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value6?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    value7?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ParameterDto
     */
    isEncrypted?: boolean;
}

/**
 * HomeControllerApi - axios parameter creator
 * @export
 */
export const HomeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeControllerApi - functional programming interface
 * @export
 */
export const HomeControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async index(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await HomeControllerApiAxiosParamCreator(configuration).index(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HomeControllerApi - factory interface
 * @export
 */
export const HomeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index(options?: any): AxiosPromise<BaseResponseString> {
            return HomeControllerApiFp(configuration).index(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeControllerApi - object-oriented interface
 * @export
 * @class HomeControllerApi
 * @extends {BaseAPI}
 */
export class HomeControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeControllerApi
     */
    public index(options?: any) {
        return HomeControllerApiFp(this.configuration).index(options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * ParamVaControllerApi - axios parameter creator
 * @export
 */
export const ParamVaControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Api to get parameter bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBankParams: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/param-va/get-bank`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Api to get param va
         * @param {GetParameterVARequest} getParameterVARequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getParamVa: async (getParameterVARequest: GetParameterVARequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getParameterVARequest' is not null or undefined
            if (getParameterVARequest === null || getParameterVARequest === undefined) {
                throw new RequiredError('getParameterVARequest','Required parameter getParameterVARequest was null or undefined when calling getParamVa.');
            }
            const localVarPath = `/v1/param-va/get-param-va`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getParameterVARequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getParameterVARequest !== undefined ? getParameterVARequest : {}) : (getParameterVARequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Api to get va params
         * @param {GetParameterRequestDto} getParameterRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVAParams: async (getParameterRequestDto: GetParameterRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getParameterRequestDto' is not null or undefined
            if (getParameterRequestDto === null || getParameterRequestDto === undefined) {
                throw new RequiredError('getParameterRequestDto','Required parameter getParameterRequestDto was null or undefined when calling getVAParams.');
            }
            const localVarPath = `/v1/param-va/get-va-params`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getParameterRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getParameterRequestDto !== undefined ? getParameterRequestDto : {}) : (getParameterRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ParamVaControllerApi - functional programming interface
 * @export
 */
export const ParamVaControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Api to get parameter bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBankParams(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetParameterListByModuleResponseDto>> {
            const localVarAxiosArgs = await ParamVaControllerApiAxiosParamCreator(configuration).getBankParams(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Api to get param va
         * @param {GetParameterVARequest} getParameterVARequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getParamVa(getParameterVARequest: GetParameterVARequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoParamVAResponse>> {
            const localVarAxiosArgs = await ParamVaControllerApiAxiosParamCreator(configuration).getParamVa(getParameterVARequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Api to get va params
         * @param {GetParameterRequestDto} getParameterRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVAParams(getParameterRequestDto: GetParameterRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetParameterListByModuleResponseDto>> {
            const localVarAxiosArgs = await ParamVaControllerApiAxiosParamCreator(configuration).getVAParams(getParameterRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ParamVaControllerApi - factory interface
 * @export
 */
export const ParamVaControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Api to get parameter bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBankParams(options?: any): AxiosPromise<BaseResponseGetParameterListByModuleResponseDto> {
            return ParamVaControllerApiFp(configuration).getBankParams(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Api to get param va
         * @param {GetParameterVARequest} getParameterVARequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getParamVa(getParameterVARequest: GetParameterVARequest, options?: any): AxiosPromise<BaseResponseGenericSingleDtoParamVAResponse> {
            return ParamVaControllerApiFp(configuration).getParamVa(getParameterVARequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Api to get va params
         * @param {GetParameterRequestDto} getParameterRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVAParams(getParameterRequestDto: GetParameterRequestDto, options?: any): AxiosPromise<BaseResponseGetParameterListByModuleResponseDto> {
            return ParamVaControllerApiFp(configuration).getVAParams(getParameterRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ParamVaControllerApi - object-oriented interface
 * @export
 * @class ParamVaControllerApi
 * @extends {BaseAPI}
 */
export class ParamVaControllerApi extends BaseAPI {
    /**
     * 
     * @summary Api to get parameter bank
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParamVaControllerApi
     */
    public getBankParams(options?: any) {
        return ParamVaControllerApiFp(this.configuration).getBankParams(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Api to get param va
     * @param {GetParameterVARequest} getParameterVARequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParamVaControllerApi
     */
    public getParamVa(getParameterVARequest: GetParameterVARequest, options?: any) {
        return ParamVaControllerApiFp(this.configuration).getParamVa(getParameterVARequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Api to get va params
     * @param {GetParameterRequestDto} getParameterRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParamVaControllerApi
     */
    public getVAParams(getParameterRequestDto: GetParameterRequestDto, options?: any) {
        return ParamVaControllerApiFp(this.configuration).getVAParams(getParameterRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * ParameterControllerApi - axios parameter creator
 * @export
 */
export const ParameterControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Api to get cutoff message
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCutOffMessage: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/parameter/get-cut-off`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Api to get all parameter by list of module
         * @param {GetParameterListByListModuleRequestDto} getParameterListByListModuleRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListParameterByListModule: async (getParameterListByListModuleRequestDto: GetParameterListByListModuleRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getParameterListByListModuleRequestDto' is not null or undefined
            if (getParameterListByListModuleRequestDto === null || getParameterListByListModuleRequestDto === undefined) {
                throw new RequiredError('getParameterListByListModuleRequestDto','Required parameter getParameterListByListModuleRequestDto was null or undefined when calling getListParameterByListModule.');
            }
            const localVarPath = `/v1/parameter/get-list-by-list-module`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getParameterListByListModuleRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getParameterListByListModuleRequestDto !== undefined ? getParameterListByListModuleRequestDto : {}) : (getParameterListByListModuleRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Api to get all parameter by module
         * @param {GetParameterRequestDto} getParameterRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListParameterByModule: async (getParameterRequestDto: GetParameterRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getParameterRequestDto' is not null or undefined
            if (getParameterRequestDto === null || getParameterRequestDto === undefined) {
                throw new RequiredError('getParameterRequestDto','Required parameter getParameterRequestDto was null or undefined when calling getListParameterByModule.');
            }
            const localVarPath = `/v1/parameter/get-list-by-module`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getParameterRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getParameterRequestDto !== undefined ? getParameterRequestDto : {}) : (getParameterRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Api to get all parameter by value
         * @param {GetParameterListByValueRequestDto} getParameterListByValueRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListParameterByModuleAndValue: async (getParameterListByValueRequestDto: GetParameterListByValueRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getParameterListByValueRequestDto' is not null or undefined
            if (getParameterListByValueRequestDto === null || getParameterListByValueRequestDto === undefined) {
                throw new RequiredError('getParameterListByValueRequestDto','Required parameter getParameterListByValueRequestDto was null or undefined when calling getListParameterByModuleAndValue.');
            }
            const localVarPath = `/v1/parameter/get-list-by-value`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getParameterListByValueRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getParameterListByValueRequestDto !== undefined ? getParameterListByValueRequestDto : {}) : (getParameterListByValueRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ParameterControllerApi - functional programming interface
 * @export
 */
export const ParameterControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Api to get cutoff message
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCutOffMessage(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await ParameterControllerApiAxiosParamCreator(configuration).getCutOffMessage(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Api to get all parameter by list of module
         * @param {GetParameterListByListModuleRequestDto} getParameterListByListModuleRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListParameterByListModule(getParameterListByListModuleRequestDto: GetParameterListByListModuleRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetParameterListByModuleResponseDto>> {
            const localVarAxiosArgs = await ParameterControllerApiAxiosParamCreator(configuration).getListParameterByListModule(getParameterListByListModuleRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Api to get all parameter by module
         * @param {GetParameterRequestDto} getParameterRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListParameterByModule(getParameterRequestDto: GetParameterRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetParameterListByModuleResponseDto>> {
            const localVarAxiosArgs = await ParameterControllerApiAxiosParamCreator(configuration).getListParameterByModule(getParameterRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Api to get all parameter by value
         * @param {GetParameterListByValueRequestDto} getParameterListByValueRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListParameterByModuleAndValue(getParameterListByValueRequestDto: GetParameterListByValueRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetParameterListByModuleResponseDto>> {
            const localVarAxiosArgs = await ParameterControllerApiAxiosParamCreator(configuration).getListParameterByModuleAndValue(getParameterListByValueRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ParameterControllerApi - factory interface
 * @export
 */
export const ParameterControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Api to get cutoff message
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCutOffMessage(options?: any): AxiosPromise<BaseResponseString> {
            return ParameterControllerApiFp(configuration).getCutOffMessage(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Api to get all parameter by list of module
         * @param {GetParameterListByListModuleRequestDto} getParameterListByListModuleRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListParameterByListModule(getParameterListByListModuleRequestDto: GetParameterListByListModuleRequestDto, options?: any): AxiosPromise<BaseResponseGetParameterListByModuleResponseDto> {
            return ParameterControllerApiFp(configuration).getListParameterByListModule(getParameterListByListModuleRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Api to get all parameter by module
         * @param {GetParameterRequestDto} getParameterRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListParameterByModule(getParameterRequestDto: GetParameterRequestDto, options?: any): AxiosPromise<BaseResponseGetParameterListByModuleResponseDto> {
            return ParameterControllerApiFp(configuration).getListParameterByModule(getParameterRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Api to get all parameter by value
         * @param {GetParameterListByValueRequestDto} getParameterListByValueRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListParameterByModuleAndValue(getParameterListByValueRequestDto: GetParameterListByValueRequestDto, options?: any): AxiosPromise<BaseResponseGetParameterListByModuleResponseDto> {
            return ParameterControllerApiFp(configuration).getListParameterByModuleAndValue(getParameterListByValueRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ParameterControllerApi - object-oriented interface
 * @export
 * @class ParameterControllerApi
 * @extends {BaseAPI}
 */
export class ParameterControllerApi extends BaseAPI {
    /**
     * 
     * @summary Api to get cutoff message
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParameterControllerApi
     */
    public getCutOffMessage(options?: any) {
        return ParameterControllerApiFp(this.configuration).getCutOffMessage(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Api to get all parameter by list of module
     * @param {GetParameterListByListModuleRequestDto} getParameterListByListModuleRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParameterControllerApi
     */
    public getListParameterByListModule(getParameterListByListModuleRequestDto: GetParameterListByListModuleRequestDto, options?: any) {
        return ParameterControllerApiFp(this.configuration).getListParameterByListModule(getParameterListByListModuleRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Api to get all parameter by module
     * @param {GetParameterRequestDto} getParameterRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParameterControllerApi
     */
    public getListParameterByModule(getParameterRequestDto: GetParameterRequestDto, options?: any) {
        return ParameterControllerApiFp(this.configuration).getListParameterByModule(getParameterRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Api to get all parameter by value
     * @param {GetParameterListByValueRequestDto} getParameterListByValueRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParameterControllerApi
     */
    public getListParameterByModuleAndValue(getParameterListByValueRequestDto: GetParameterListByValueRequestDto, options?: any) {
        return ParameterControllerApiFp(this.configuration).getListParameterByModuleAndValue(getParameterListByValueRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


