import * as Yup from 'yup';


export const generalInformationSchema = Yup.object().shape({
  generalInformation: Yup.object().shape({
    address: Yup.string().required('required'),
    alias: Yup.string().nullable(),
    branchCode: Yup.string().required('required'),
    cellularContactPerson: Yup.object().shape({
      areaCode: Yup.string().nullable(),
      number: Yup.string().nullable(),
    }),
    cif: Yup.string().nullable(),
    city: Yup.mixed().required('required'),
    contactPerson: Yup.string().required('required'),
    country: Yup.mixed().required('required'),
    customerId: Yup.string().nullable(),
    customerName: Yup.string().required('required'),
    customerRemark: Yup.string().nullable(),
    dataSource: Yup.string().nullable(),
    debtorOwnerships: Yup.string().nullable(),
    debtorPurpose: Yup.string().nullable(),
    debtorType: Yup.string().notRequired().nullable(),
    defineSector: Yup.string().nullable(),
    district: Yup.mixed().required('required'),
    email: Yup.string().nullable().email('invalid email'),
    emailContactPerson: Yup.string().nullable().email('invalid email'),
    goPublic: Yup.string().required('required'),
    infrastructureSector: Yup.mixed().required('required'),
    institutionType: Yup.string().required('required'),
    isGroup: Yup.string().required('required'),
    isNew: Yup.string().nullable(),
    isRelatedSmi: Yup.string().required('required'),
    language: Yup.array().nullable().default([]),
    modifiedBy: Yup.string().nullable(),
    modifiedDate: Yup.string().nullable(),
    nationality: Yup.mixed().nullable(),
    officeCellular: Yup.object().shape({
      areaCode: Yup.string().nullable(),
      number: Yup.string().nullable(),
    }),
    officeCellularContactPerson: Yup.object().shape({
      areaCode: Yup.string().required('required'),
      ext: Yup.string().required('required'),
      number: Yup.string().required('required'),
    }),
    positionContactPerson: Yup.string().required('required'),
    postalCode: Yup.mixed().required('required'),
    province: Yup.mixed().required('required'),
    status: Yup.string().nullable(),
    subDistrict: Yup.mixed().required('required'),
    telephone: Yup.object().shape({
      areaCode: Yup.string().required('required'),
      ext: Yup.string().nullable(),
      number: Yup.string().required('required'),
    }),
    website: Yup.string().nullable(),
  }),
});
