export const action = {
  CANCELED: 'CANCEL',
  FINAL: 'FINAL',
  KADIV_TO_TL: 'RETURN_TO_TL',
  REJECTED: 'REJECT',
  RETURN_STAFF: 'RETURN_TO_STAFF',
  RETURN_TO_MAKER: 'RETURN_TO_MAKER',
  REVISION: 'REVISION',
  SAVE: 'SAVE',
  SAVE_NEXT: 'SAVE_NEXT',
  SUBMIT: 'SUBMIT',
};
