export const ENCRYPT_KEY = 'secret';

export const APP_CONTEXT_PERSIST = 'app-context-persist';

export const TOKEN = 'accessToken';

export const roles = {
  ALL: 'All',
  ANALYST: 'Analyst',
  BOD: 'BOD',
  CHECKER: 'CHECKER',
  KADIV: 'KADIV',
  MAKER: 'MAKER',
  RM: 'STAFF',
  RM_CC: 'RM Credit Checking',
  STAFF: 'STAFF',
  SUPER_ADMIN: 'Super Admin',
  TL: 'TL',
  TL_ANALYST: 'TL Analyst',
};

export const positions = {
  ALL: 'ALL',
  ANALYST: 'ANALYST',
  INTERNAL_GUEST: 'INTERNAL_GUEST',
  KADIV: 'KADIV',
  RM: 'RM',
  TL: 'TL',
};

export const ONE_MINUTE = 1 * 60 * 1000;
export const FIVE_SECONDS = 5 * 1000;

export const CURRENCY_LIST = [
  {
    label: 'IDR',
    value: 'IDR',
  },
  {
    label: 'USD',
    value: 'USD',
  },
];

export const MAX_STEP_PERCENTAGE = 100;

export const REGEX_ALPHANUM_SPECIAL_CHAR = /^\s|[^\w\d\s!@#$%^&*()_+{}\[\]:;<>,.?~\\/\|=-]/g;

export const CLOSE = 'CLOSE';
export const END_PROCESS = 'END_PROCESS';
export const EDIT = 'EDIT';
export const SAVE = 'SAVE';
export const CANCELED = 'CANCELED';
export const DECLINE = 'DECLINE';
export const REJECTED = 'REJECTED';
export const SUBMIT = 'SUBMIT';
export const SUBMIT_ASK_FOR_INFO = 'SUBMIT_ASK_FOR_INFO';
export const RETURN_TO_STAFF = 'RETURN_TO_STAFF';
export const RETURN_TO_TL = 'RETURN_TO_TL';
export const RETURN_TO_MAKER = 'RETURN_TO_MAKER';
export const RETURN_TO_ANALYST = 'RETURN_TO_ANALYST';
export const ASK_FOR_INFO = 'ASK_FOR_INFO';
export const ASK_FOR_INFO_SUMMARY = 'ASK_FOR_INFO_SUMMARY';
export const ASK_FOR_INFO_SUMMARY_TL_DPOP = 'ASK_FOR_INFO_SUMMARY_TL_DPOP';
export const ASK_FOR_INFO_SUMMARY_KADIV_DPOP = 'ASK_FOR_INFO_SUMMARY_KADIV_DPOP';
export const ASK_FOR_INFO_SUMMARY_TL = 'ASK_FOR_INFO_SUMMARY_TL';
export const ASK_FOR_INFO_SUMMARY_KADIV = 'ASK_FOR_INFO_SUMMARY_KADIV';
export const ASK_FOR_INFO_TL = 'ASK_FOR_INFO_TL';
export const ASK_FOR_INFO_KADIV = 'ASK_FOR_INFO_KADIV';
export const ASK_FOR_INFO_TL_DPOP = 'ASK_FOR_INFO_TL_DPOP';
export const ASK_FOR_INFO_KADIV_DPOP = 'ASK_FOR_INFO_KADIV_DPOP';
export const APPROVE_ASK_FOR_INFO = 'APPROVE_ASK_FOR_INFO';
export const GENERATE_DRAFT_MEMO = 'GENERATE_DRAFT_MEMO';
export const BUSINESS_DIVISION = 'BUSINESS_DIVISION';
export const DPOP_DIVISION = 'DPOP_DIVISION';
export const DEPI_DIVISION = 'DEPI_DIVISION';
export const RETURN_TO_STAFF_DPOP = 'RETURN_TO_STAFF_DPOP';
export const RETURN_TO_TL_DPOP = 'RETURN_TO_TL_DPOP';
export const BAST_DONE = 'BAST_DONE';
export const APPROVE = 'APPROVE';
export const COMPLETE = 'COMPLETE';
export const SECOND_FINANCING_DIVISION = 'SECOND_FINANCING_DIVISION';
export const DP_2_DIVISION = 'DP 2_DIVISION';
export const DPB_DIVISION = 'DPB_DIVISION';
export const DUS_DIVISION = 'DUS_DIVISION';
export const DPPU_1_DIVISION = 'DPPU_1_DIVISION';
export const DPPU_2_DIVISION = 'DPPU_2_DIVISION';
export const DPPU_3_DIVISION = 'DPPU_3_DIVISION';
export const WAITING_APPROVAL_TL = 'WAITING_APPROVAL_TL';
export const WAITING_APPROVAL_TL_CANCELED = 'WAITING_APPROVAL_TL_CANCELED';
export const WAITING_APPROVAL_TL_END_ASSIGNMENT = 'WAITING_APPROVAL_TL_END_ASSIGNMENT';
export const WAITING_APPROVAL_RECEIVE_KADIV_CANCELED = 'WAITING_APPROVAL_RECEIVE_KADIV_CANCELED';
export const WAITING_APPROVAL_RECEIVE_KADIV_END_ASSIGNMENT = 'WAITING_APPROVAL_RECEIVE_KADIV_END_ASSIGNMENT';
export const WAITING_APPROVAL_CHECKER = 'WAITING_APPROVAL_CHECKER';
export const WAITING_APPROVAL_CHECKER_CANCELED = 'WAITING_APPROVAL_CHECKER_CANCELED';
export const WAITING_APPROVAL_CHECKER_END_ASSIGNMENT = 'WAITING_APPROVAL_CHECKER_END_ASSIGNMENT';
export const WAITING_APPROVAL_RECEIVE_KADIV_MAKER = 'WAITING_APPROVAL_RECEIVE_KADIV_MAKER';
export const WAITING_APPROVAL_RECEIVE_KADIV_MAKER_CANCELED = 'WAITING_APPROVAL_RECEIVE_KADIV_MAKER_CANCELED';
export const WAITING_APPROVAL_RECEIVE_KADIV_MAKER_END = 'WAITING_APPROVAL_RECEIVE_KADIV_MAKER_END';
export const RETURN_TO_REQUESTOR_MAKER = 'RETURN_TO_REQUESTOR_MAKER';
export const PEMDA = 'PEMDA';
export const PUBLIC = 'PUBLIC';
export const DRAFT = 'DRAFT';
export const DTI_DIVISION = 'DTI_DIVISION';
export const DK_DIVISION = 'DK_DIVISION';
export const DKHI_DIVISION = 'DKHI_DIVISION';
export const DPPIK_DIVISION = 'DPPIK_DIVISION';
export const DH_DIVISION = 'DH_DIVISION';
export const DELST_DIVISION = 'DELST_DIVISION';
export const BoD_GROUP = 'BoD_GROUP';
export const DAA_DIVISION = 'DAA_DIVISION';
export const DAI_DIVISION = 'DAI_DIVISION';
export const DJK_DIVISION = 'DJK_DIVISION';
export const DMRT_DIVISION = 'DMRT_DIVISION';
export const DPKMI_DIVISION = 'DPKMI_DIVISION';
export const DPM_DIVISION = 'DPM_DIVISION';
export const EXTERNAL_GROUP = 'EXTERNAL_GROUP';
export const GENERAL_DIVISION = 'GENERAL_DIVISION';
export const PROJECT_DIVISION = 'PROJECT_DIVISION';
export const RND_ECONOMIC_DIVISION = 'RND_ECONOMIC_DIVISION';
export const SCR_DIVISION = 'SCR_DIVISION';
export const SDM_DIVISION = 'SDM_DIVISION';
export const SUPER_DIVISION = 'SUPER_DIVISION';
export const COMPLETED = 'COMPLETED';
export const APPROVED = 'APPROVED';
export const DEPI_DRD_OK = 'DEPI_DRD_OK';
export const DEPI_DRD_NOT_OK = 'DEPI_DRD_NOT_OK';
export const DRD_OK = 'DRD_OK';
export const DRD_NOT_OK = 'DRD_NOT_OK';
export const RETURN_TO_REQUESTOR = 'RETURN_TO_REQUESTOR';
export const WAITING_APPROVAL_RECEIVE_KADIV = 'WAITING_APPROVAL_RECEIVE_KADIV';
export const REJECTED_FROM_ELO = 'REJECTED_FROM_ELO';
export const WAITING_CIF = 'WAITING_CIF';
export const WAITING_ASK_FOR_INFO_APPROVAL_KADIV = 'WAITING_ASK_FOR_INFO_APPROVAL_KADIV';
export const WAITING_ASK_FOR_INFO_RESPONSE = 'WAITING_ASK_FOR_INFO_RESPONSE';
export const WAITING_ASK_FOR_INFO_APPROVAL_KADIV_RESPONSE = 'WAITING_ASK_FOR_INFO_APPROVAL_KADIV_RESPONSE';
export const WAITING_ASK_FOR_INFO_APPROVAL_TL_RESPONSE = 'WAITING_ASK_FOR_INFO_APPROVAL_TL_RESPONSE';
export const ASK_FOR_INFO_RESPONSE_RETURN_TO_STAFF = 'ASK_FOR_INFO_RESPONSE_RETURN_TO_STAFF';
export const ASK_FOR_INFO_RESPONSE_RETURN_TO_TL = 'ASK_FOR_INFO_RESPONSE_RETURN_TO_TL';

export const SYNCFUSION_SERVICE_URL = `${process.env.NEXT_PUBLIC_BASE_URL}/api/documenteditor/`;

export const BUSINESS_DIVISION_LIST = [
  BUSINESS_DIVISION,
  SECOND_FINANCING_DIVISION,
  DP_2_DIVISION,
  DPB_DIVISION,
  DUS_DIVISION,
  DPPU_1_DIVISION,
  DPPU_2_DIVISION,
  DPPU_3_DIVISION,
];
