export const MAINTENANCE_MODULE = {
  CREDIT_CHECKING_DOCUMENT: 'CREDIT_CHECKING_DOCUMENT',
  CREDIT_CHECKING_REQUEST: 'CREDIT_CHECKING_REQUEST',
  CREDIT_CHECKING_RESULT: 'CREDIT_CHECKING_RESULT',
  MAINTENANCE_DEBTOR: 'MAINTENANCE_DEBTOR',
  MASTER_DATA: 'MASTER_DATA',
  MIP: 'MIP',
  MIP_REVIEW: 'MIP_REVIEW',
};


export const MAINTENANCE_STATUS = {
  APPROVED_MAINTENANCE_DEBTOR: 'APPROVED_MAINTENANCE_DEBTOR',
  MAINTENANCE_DEBTOR_CREATION: 'MAINTENANCE_DEBTOR_CREATION',
  RETURN_TO_STAFF_MAINTENANCE_DEBTOR: 'RETURN_TO_STAFF_MAINTENANCE_DEBTOR',
  WAITING_APPROVAL_TL_MAINTENANCE_DEBTOR: 'WAITING_APPROVAL_TL_MAINTENANCE_DEBTOR',
};

export const MAINTENANCE_STATUS_LABEL = {
  [MAINTENANCE_STATUS.MAINTENANCE_DEBTOR_CREATION]: 'Maintenance Customer Creation',
  [MAINTENANCE_STATUS.WAITING_APPROVAL_TL_MAINTENANCE_DEBTOR]: 'Waiting Approval TL',
  [MAINTENANCE_STATUS.APPROVED_MAINTENANCE_DEBTOR]: 'Approved Maintenance Customer',
  [MAINTENANCE_STATUS.RETURN_TO_STAFF_MAINTENANCE_DEBTOR]: 'Return to Staff',
};
