export const SITEVISIT_STATUS = {
  APPROVED_SITE_VISIT: 'APPROVED_SITE_VISIT',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED',
  RETURN_TO_STAFF: 'RETURN_TO_STAFF',
  SITE_VISIT_CREATION: 'SITE_VISIT_CREATION',
  WAITING_APPROVAL_CHECKER: 'WAITING_APPROVAL_CHECKER',
  WAITING_APPROVAL_TL: 'WAITING_APPROVAL_TL',
};

export const SITEVISIT_STATUS_LABEL = {
  [SITEVISIT_STATUS.SITE_VISIT_CREATION]: 'Entry Site Visit Result',
  [SITEVISIT_STATUS.WAITING_APPROVAL_TL]: 'Waiting Approval TL',
  [SITEVISIT_STATUS.WAITING_APPROVAL_CHECKER]: 'Waiting Approval Checker',
  [SITEVISIT_STATUS.RETURN_TO_STAFF]: 'Return To Staff',
  [SITEVISIT_STATUS.APPROVED_SITE_VISIT]: 'Completed',
  [SITEVISIT_STATUS.REJECTED]: 'Rejected',
  [SITEVISIT_STATUS.CANCELED]: 'Canceled',
};

export const SITEVISIT_STATUS_COLOR = {
  APPROVED_SITE_VISIT: 'primary',
  CANCELED: 'error',
  REJECTED: 'error',
  RETURN_TO_STAFF: 'primary',
  SITE_VISIT_CREATION: 'primary',
  WAITING_APPROVAL_CHECKER: 'primary',
  WAITING_APPROVAL_TL: 'primary',
};
