export const MODAL_ID = {
  ADD_LPA: 'ADD_LPA',
  DETAIL_FACILITY: 'DETAIL_FACILITY',
  FORM_FACILITY: 'FORM_FACILITY',
  LPA_DETAIL: 'LPA_DETAIL',
  TABLE_PAYMENT_FACILITY_EXISTING: 'TABLE_PAYMENT_FACILITY_EXISTING',
};
