export const PIPELINE_STATUS = {
  APPROVED_PIPELINE: 'APPROVED_PIPELINE',
  CANCELLED: 'CANCELLED',
  PIPELINE_CREATION: 'PIPELINE_CREATION',
  PROCESS_TO_NEXT_STAGES: 'PROCESS_TO_NEXT_STAGES',
  REJECTED: 'REJECTED',
  RETURN_TO_STAFF: 'RETURN_TO_STAFF',
  WAITING_APPROVAL_TL: 'WAITING_APPROVAL_TL',
};

export const PIPELINE_STATUS_LABEL = {
  [PIPELINE_STATUS.PIPELINE_CREATION]: 'Pipeline Creation',
  [PIPELINE_STATUS.RETURN_TO_STAFF]: 'Return to Staff',
  [PIPELINE_STATUS.REJECTED]: 'Rejected',
  [PIPELINE_STATUS.CANCELLED]: 'Cancelled',
  [PIPELINE_STATUS.WAITING_APPROVAL_TL]: 'Waiting Approval TL',
  [PIPELINE_STATUS.APPROVED_PIPELINE]: 'Approved Pipeline',
  [PIPELINE_STATUS.PROCESS_TO_NEXT_STAGES]: 'Proccess to Next Stages',
};

export const PIPELINE_STATUS_COLOR = {
  APPROVED_PIPELINE: 'primary',
  CANCELLED: 'error',
  PIPELINE_CREATION: 'disabled',
  PROCESS_TO_NEXT_STAGES: 'primary',
  REJECTED: 'error',
  RETURN_TO_STAFF: 'primary',
  WAITING_APPROVAL_TL: 'primary',
};
