enum TypeDivision {
  DK_DIVISION = 'DK_DIVISION',
  SECOND_DELST_DIVISION = 'SECOND_DELST_DIVISION',
  DEPI_DIVISION = 'DEPI_DIVISION',
  DPOP_DIVISION = 'DPOP_DIVISION',
  DELST_DIVISION = 'DELST_DIVISION',
  BUSINESS_DIVISION = 'BUSINESS_DIVISION',
}

export { TypeDivision };
