export enum TypePosition {
  ACCOUNTANT = 'ACCOUNTANT',
  ADMIN_ASSET = 'ADMIN_ASSET',
  ANALYST = 'ANALYST',
  CC = 'CC',
  DHPI = 'DHPI',
  ELO = 'ELO',
  ESDD = 'ESDD',
  STAFF_ESDD = 'STAFF_ESDD',
  FM = 'FM',
  STAFF_FM = 'STAFF_FM',
  GUEST = 'GUEST',
  HIGH_RISK = 'HIGH_RISK',
  IOU = 'IOU',
  MIS = 'MIS',
  PD = 'PD',
  PJ = 'PJ',
  Staff_PJ_LPA = 'Staff_PJ_LPA',
  RM = 'RM',
  SPECIALIST = 'SPECIALIST',
  TECHNICAL = 'TECHNICAL'
}
