export const mockTableDataResultList = [
  {
    aging: '1 Hari 2 Jam 15 menit',
    createdDate: '23 Maret 2023',
    debtorName: 'Bappenas',
    division: '[Divisi]',
    dueDate: '11 Januari 2024',
    id: '0125102023',
    rmName: '[nama rm]',
    status: 'APPROVAL_TL',
    statusLabel: 'Approval TL',
  },
  {
    aging: '1 Hari 2 Jam 15 menit',
    createdDate: '23 Maret 2023',
    debtorName: 'Adimitra Energi Hidro',
    division: '[Divisi]',
    dueDate: '11 Januari 2024',
    id: '0125102024',
    rmName: '[nama rm]',
    status: 'APPROVAL_KADIV',
    statusLabel: 'Approval Kadiv',
  },
  {
    aging: '1 Hari 2 Jam 15 menit',
    createdDate: '23 Maret 2023',
    debtorName: 'Angkasa Pura I (Persero)',
    division: '[Divisi]',
    dueDate: '11 Januari 2024',
    id: '0125102025',
    rmName: '[nama rm]',
    status: 'APPROVAL_KADIV',
    statusLabel: 'Approval Kadiv',
  },
];
