// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AccessManagement
 */
export interface AccessManagement {
    /**
     * 
     * @type {string}
     * @memberof AccessManagement
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessManagement
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof AccessManagement
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AccessManagement
     */
    userId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AccessManagement
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AccessManagement
     */
    accessType?: AccessManagementAccessTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AccessManagement
     */
    permissionAccess?: number;
    /**
     * 
     * @type {string}
     * @memberof AccessManagement
     */
    expiredDate?: string;
    /**
     * 
     * @type {number}
     * @memberof AccessManagement
     */
    fromUser?: number;
    /**
     * 
     * @type {Division}
     * @memberof AccessManagement
     */
    userDivision?: Division;
    /**
     * 
     * @type {Group}
     * @memberof AccessManagement
     */
    userGroup?: Group;
    /**
     * 
     * @type {RoleRefactor}
     * @memberof AccessManagement
     */
    userRoleRefactor?: RoleRefactor;
    /**
     * 
     * @type {Array<Position>}
     * @memberof AccessManagement
     */
    userPosition?: Array<Position>;
    /**
     * 
     * @type {UserV2}
     * @memberof AccessManagement
     */
    userSuperior?: UserV2;
}

/**
    * @export
    * @enum {string}
    */
export enum AccessManagementAccessTypeEnum {
    PERMANENT = 'PERMANENT',
    TEMPORARY = 'TEMPORARY'
}

/**
 * 
 * @export
 * @interface AuthLogin2FARequestDto
 */
export interface AuthLogin2FARequestDto {
    /**
     * 
     * @type {string}
     * @memberof AuthLogin2FARequestDto
     */
    tokenSession?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLogin2FARequestDto
     */
    tokenProvider?: string;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoBoolean
 */
export interface BaseResponseGenericSingleDtoBoolean {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoBoolean}
     * @memberof BaseResponseGenericSingleDtoBoolean
     */
    data?: GenericSingleDtoBoolean;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoOtpResponseDto
 */
export interface BaseResponseGenericSingleDtoOtpResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoOtpResponseDto}
     * @memberof BaseResponseGenericSingleDtoOtpResponseDto
     */
    data?: GenericSingleDtoOtpResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseLoginResponseDto
 */
export interface BaseResponseLoginResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLoginResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLoginResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLoginResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLoginResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLoginResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLoginResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {LoginResponseDto}
     * @memberof BaseResponseLoginResponseDto
     */
    data?: LoginResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseLogoutResponseDto
 */
export interface BaseResponseLogoutResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLogoutResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLogoutResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLogoutResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLogoutResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLogoutResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseLogoutResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {LogoutResponseDto}
     * @memberof BaseResponseLogoutResponseDto
     */
    data?: LogoutResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseString
 */
export interface BaseResponseString {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    data?: string;
}
/**
 * 
 * @export
 * @interface BaseResponseUserDetailv2Response
 */
export interface BaseResponseUserDetailv2Response {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDetailv2Response
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDetailv2Response
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDetailv2Response
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDetailv2Response
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDetailv2Response
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDetailv2Response
     */
    timestamp?: string;
    /**
     * 
     * @type {UserDetailv2Response}
     * @memberof BaseResponseUserDetailv2Response
     */
    data?: UserDetailv2Response;
}
/**
 * 
 * @export
 * @interface BaseResponseUserV2
 */
export interface BaseResponseUserV2 {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserV2
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserV2
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserV2
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserV2
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserV2
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserV2
     */
    timestamp?: string;
    /**
     * 
     * @type {UserV2}
     * @memberof BaseResponseUserV2
     */
    data?: UserV2;
}
/**
 * 
 * @export
 * @interface BaseResponseValidateResponseDto
 */
export interface BaseResponseValidateResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseValidateResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseValidateResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseValidateResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseValidateResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseValidateResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseValidateResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {ValidateResponseDto}
     * @memberof BaseResponseValidateResponseDto
     */
    data?: ValidateResponseDto;
}
/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    categoryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    name?: string;
}
/**
 * 
 * @export
 * @interface CreateNewPasswordRequest
 */
export interface CreateNewPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNewPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNewPasswordRequest
     */
    confirmPassword: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNewPasswordRequest
     */
    currentPassword?: string;
}
/**
 * 
 * @export
 * @interface Directorate
 */
export interface Directorate {
    /**
     * 
     * @type {string}
     * @memberof Directorate
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Directorate
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Directorate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Directorate
     */
    directorateCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Directorate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Directorate
     */
    type?: string;
}
/**
 * 
 * @export
 * @interface Division
 */
export interface Division {
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Division
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    divisionCode?: string;
    /**
     * 
     * @type {Category}
     * @memberof Division
     */
    category?: Category;
    /**
     * 
     * @type {Directorate}
     * @memberof Division
     */
    directorate?: Directorate;
    /**
     * 
     * @type {Group}
     * @memberof Division
     */
    group?: Group;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    segmentFinance?: string;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoBoolean
 */
export interface GenericSingleDtoBoolean {
    /**
     * 
     * @type {boolean}
     * @memberof GenericSingleDtoBoolean
     */
    content?: boolean;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoOtpResponseDto
 */
export interface GenericSingleDtoOtpResponseDto {
    /**
     * 
     * @type {OtpResponseDto}
     * @memberof GenericSingleDtoOtpResponseDto
     */
    content?: OtpResponseDto;
}
/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    type?: string;
}
/**
 * 
 * @export
 * @interface GroupMenuApps
 */
export interface GroupMenuApps {
    /**
     * 
     * @type {string}
     * @memberof GroupMenuApps
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMenuApps
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupMenuApps
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupMenuApps
     */
    groupMenuCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMenuApps
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMenuApps
     */
    description?: string;
}
/**
 * 
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDto
     */
    password?: string;
}
/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    token?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseDto
     */
    needPassword?: boolean;
    /**
     * 
     * @type {number}
     * @memberof LoginResponseDto
     */
    totalAttemptsPasswordFailed?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseDto
     */
    otp?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    redirectSSO?: string;
    /**
     * 
     * @type {UserDetailResponse}
     * @memberof LoginResponseDto
     */
    user?: UserDetailResponse;
    /**
     * 
     * @type {Array<RoleDto>}
     * @memberof LoginResponseDto
     */
    listRole?: Array<RoleDto>;
    /**
     * 
     * @type {Array<UserGroupDto>}
     * @memberof LoginResponseDto
     */
    listUserGroup?: Array<UserGroupDto>;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseDto
     */
    needChangePassword?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseDto
     */
    ldap?: boolean;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof LoginResponseDto
     */
    additionalData?: { [key: string]: object; };
}
/**
 * 
 * @export
 * @interface LogoutRequestDto
 */
export interface LogoutRequestDto {
    /**
     * 
     * @type {string}
     * @memberof LogoutRequestDto
     */
    token?: string;
}
/**
 * 
 * @export
 * @interface LogoutResponseDto
 */
export interface LogoutResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof LogoutResponseDto
     */
    isSuccess?: boolean;
}
/**
 * 
 * @export
 * @interface OtpRequestDto
 */
export interface OtpRequestDto {
    /**
     * 
     * @type {string}
     * @memberof OtpRequestDto
     */
    otp?: string;
}
/**
 * 
 * @export
 * @interface OtpResponseDto
 */
export interface OtpResponseDto {
    /**
     * 
     * @type {string}
     * @memberof OtpResponseDto
     */
    token?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OtpResponseDto
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OtpResponseDto
     */
    expired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OtpResponseDto
     */
    locked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OtpResponseDto
     */
    lockedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof OtpResponseDto
     */
    startDateRequestOtp?: string;
    /**
     * 
     * @type {number}
     * @memberof OtpResponseDto
     */
    remaining?: number;
    /**
     * 
     * @type {number}
     * @memberof OtpResponseDto
     */
    totalAttempts?: number;
    /**
     * 
     * @type {number}
     * @memberof OtpResponseDto
     */
    failedAttempts?: number;
    /**
     * 
     * @type {number}
     * @memberof OtpResponseDto
     */
    maxAttempts?: number;
    /**
     * 
     * @type {UserDetailResponse}
     * @memberof OtpResponseDto
     */
    user?: UserDetailResponse;
    /**
     * 
     * @type {Array<RoleDto>}
     * @memberof OtpResponseDto
     */
    listRole?: Array<RoleDto>;
    /**
     * 
     * @type {Array<UserGroupDto>}
     * @memberof OtpResponseDto
     */
    listUserGroup?: Array<UserGroupDto>;
    /**
     * 
     * @type {boolean}
     * @memberof OtpResponseDto
     */
    needChangePassword?: boolean;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof OtpResponseDto
     */
    additionalData?: { [key: string]: object; };
}
/**
 * 
 * @export
 * @interface Position
 */
export interface Position {
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    positionCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    division?: string;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    type?: string;
}
/**
 * 
 * @export
 * @interface RoleDto
 */
export interface RoleDto {
    /**
     * 
     * @type {number}
     * @memberof RoleDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleDto
     */
    roleCode?: string;
}
/**
 * 
 * @export
 * @interface RoleRefactor
 */
export interface RoleRefactor {
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof RoleRefactor
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    roleCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRefactor
     */
    superiorRole?: string;
}
/**
 * 
 * @export
 * @interface UserDetailResponse
 */
export interface UserDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    nik?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    status?: UserDetailResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    statusLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    privyId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    skill?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    lastLoginDate?: string;
    /**
     * 
     * @type {RoleRefactor}
     * @memberof UserDetailResponse
     */
    roleRefactor?: RoleRefactor;
    /**
     * 
     * @type {Array<Division>}
     * @memberof UserDetailResponse
     */
    division?: Array<Division>;
    /**
     * 
     * @type {Array<Position>}
     * @memberof UserDetailResponse
     */
    position?: Array<Position>;
    /**
     * 
     * @type {UserDetailSubData}
     * @memberof UserDetailResponse
     */
    superior?: UserDetailSubData;
    /**
     * 
     * @type {Array<GroupMenuApps>}
     * @memberof UserDetailResponse
     */
    groupMenuApps?: Array<GroupMenuApps>;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    userFrom?: UserDetailResponseUserFromEnum;
    /**
     * 
     * @type {string}
     * @memberof UserDetailResponse
     */
    bucketProcessId?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum UserDetailResponseStatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'IN_ACTIVE',
    BLOCKEDOTPREQUEST = 'BLOCKED_OTP_REQUEST',
    SUSPEND = 'SUSPEND'
}
/**
    * @export
    * @enum {string}
    */
export enum UserDetailResponseUserFromEnum {
    NEWLOS = 'NEW_LOS',
    LDAP = 'LDAP',
    NONLDAP = 'NON_LDAP',
    INTERNAL = 'INTERNAL',
    EXTERNAL = 'EXTERNAL'
}

/**
 * 
 * @export
 * @interface UserDetailSubData
 */
export interface UserDetailSubData {
    /**
     * 
     * @type {string}
     * @memberof UserDetailSubData
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailSubData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailSubData
     */
    nik?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailSubData
     */
    userId?: string;
}
/**
 * 
 * @export
 * @interface UserDetailv2Response
 */
export interface UserDetailv2Response {
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    nik?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    status?: UserDetailv2ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    statusLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    privyId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    skill?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    lastLoginDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    userFrom?: UserDetailv2ResponseUserFromEnum;
    /**
     * 
     * @type {string}
     * @memberof UserDetailv2Response
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {AccessManagement}
     * @memberof UserDetailv2Response
     */
    accessManagementActive?: AccessManagement;
    /**
     * 
     * @type {Array<AccessManagement>}
     * @memberof UserDetailv2Response
     */
    accessManagements?: Array<AccessManagement>;
}

/**
    * @export
    * @enum {string}
    */
export enum UserDetailv2ResponseStatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'IN_ACTIVE',
    BLOCKEDOTPREQUEST = 'BLOCKED_OTP_REQUEST',
    SUSPEND = 'SUSPEND'
}
/**
    * @export
    * @enum {string}
    */
export enum UserDetailv2ResponseUserFromEnum {
    NEWLOS = 'NEW_LOS',
    LDAP = 'LDAP',
    NONLDAP = 'NON_LDAP',
    INTERNAL = 'INTERNAL',
    EXTERNAL = 'EXTERNAL'
}

/**
 * 
 * @export
 * @interface UserGroupDto
 */
export interface UserGroupDto {
    /**
     * 
     * @type {number}
     * @memberof UserGroupDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserGroupDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGroupDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGroupDto
     */
    divisionCode?: string;
}
/**
 * 
 * @export
 * @interface UserV2
 */
export interface UserV2 {
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof UserV2
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    userType?: UserV2UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    nik?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    privyId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    agency?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    status?: UserV2StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    skill?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UserV2
     */
    accessManagementIdActing?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserV2
     */
    needChangePassword?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    lastChangePassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    lastGetOTP?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    lastLogin?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    lastLogout?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2
     */
    lastApprovedDate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserV2
     */
    isDeleted?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum UserV2UserTypeEnum {
    NEWLOS = 'NEW_LOS',
    LDAP = 'LDAP',
    NONLDAP = 'NON_LDAP',
    INTERNAL = 'INTERNAL',
    EXTERNAL = 'EXTERNAL'
}
/**
    * @export
    * @enum {string}
    */
export enum UserV2StatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'IN_ACTIVE',
    BLOCKEDOTPREQUEST = 'BLOCKED_OTP_REQUEST',
    SUSPEND = 'SUSPEND'
}

/**
 * 
 * @export
 * @interface ValidateRequestDto
 */
export interface ValidateRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ValidateRequestDto
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateRequestDto
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidateRequestDto
     */
    listRequiredType?: Array<string>;
}
/**
 * 
 * @export
 * @interface ValidateResponseDto
 */
export interface ValidateResponseDto {
    /**
     * 
     * @type {LoginResponseDto}
     * @memberof ValidateResponseDto
     */
    userData?: LoginResponseDto;
}

/**
 * AuthControllerApi - axios parameter creator
 * @export
 */
export const AuthControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get token for application
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSessionLogin: async (loginRequestDto: LoginRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequestDto' is not null or undefined
            if (loginRequestDto === null || loginRequestDto === undefined) {
                throw new RequiredError('loginRequestDto','Required parameter loginRequestDto was null or undefined when calling authSessionLogin.');
            }
            const localVarPath = `/v1/auth/provider/session`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof loginRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(loginRequestDto !== undefined ? loginRequestDto : {}) : (loginRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to validate token for application
         * @param {AuthLogin2FARequestDto} authLogin2FARequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSessionLoginValidate: async (authLogin2FARequestDto: AuthLogin2FARequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'authLogin2FARequestDto' is not null or undefined
            if (authLogin2FARequestDto === null || authLogin2FARequestDto === undefined) {
                throw new RequiredError('authLogin2FARequestDto','Required parameter authLogin2FARequestDto was null or undefined when calling authSessionLoginValidate.');
            }
            const localVarPath = `/v1/auth/provider/session/validate`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof authLogin2FARequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(authLogin2FARequestDto !== undefined ? authLogin2FARequestDto : {}) : (authLogin2FARequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary SAML Success
         * @param {object} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        azureCallback: async (request: object, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            if (request === null || request === undefined) {
                throw new RequiredError('request','Required parameter request was null or undefined when calling azureCallback.');
            }
            const localVarPath = `/v1/auth/saml/callback/azure`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (request !== undefined) {
                localVarQueryParameter['request'] = request;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to revoke token
         * @param {LogoutRequestDto} logoutRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (logoutRequestDto: LogoutRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'logoutRequestDto' is not null or undefined
            if (logoutRequestDto === null || logoutRequestDto === undefined) {
                throw new RequiredError('logoutRequestDto','Required parameter logoutRequestDto was null or undefined when calling logout.');
            }
            const localVarPath = `/v1/auth/logout`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof logoutRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(logoutRequestDto !== undefined ? logoutRequestDto : {}) : (logoutRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to check processor service is running
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ping: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/auth/ping`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to validate token
         * @param {ValidateRequestDto} validateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validate: async (validateRequestDto: ValidateRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'validateRequestDto' is not null or undefined
            if (validateRequestDto === null || validateRequestDto === undefined) {
                throw new RequiredError('validateRequestDto','Required parameter validateRequestDto was null or undefined when calling validate.');
            }
            const localVarPath = `/v1/auth/validate`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof validateRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(validateRequestDto !== undefined ? validateRequestDto : {}) : (validateRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthControllerApi - functional programming interface
 * @export
 */
export const AuthControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get token for application
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSessionLogin(loginRequestDto: LoginRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLoginResponseDto>> {
            const localVarAxiosArgs = await AuthControllerApiAxiosParamCreator(configuration).authSessionLogin(loginRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to validate token for application
         * @param {AuthLogin2FARequestDto} authLogin2FARequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSessionLoginValidate(authLogin2FARequestDto: AuthLogin2FARequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLoginResponseDto>> {
            const localVarAxiosArgs = await AuthControllerApiAxiosParamCreator(configuration).authSessionLoginValidate(authLogin2FARequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary SAML Success
         * @param {object} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async azureCallback(request: object, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await AuthControllerApiAxiosParamCreator(configuration).azureCallback(request, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to revoke token
         * @param {LogoutRequestDto} logoutRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(logoutRequestDto: LogoutRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLogoutResponseDto>> {
            const localVarAxiosArgs = await AuthControllerApiAxiosParamCreator(configuration).logout(logoutRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to check processor service is running
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ping(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await AuthControllerApiAxiosParamCreator(configuration).ping(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to validate token
         * @param {ValidateRequestDto} validateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validate(validateRequestDto: ValidateRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseValidateResponseDto>> {
            const localVarAxiosArgs = await AuthControllerApiAxiosParamCreator(configuration).validate(validateRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AuthControllerApi - factory interface
 * @export
 */
export const AuthControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to get token for application
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSessionLogin(loginRequestDto: LoginRequestDto, options?: any): AxiosPromise<BaseResponseLoginResponseDto> {
            return AuthControllerApiFp(configuration).authSessionLogin(loginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to validate token for application
         * @param {AuthLogin2FARequestDto} authLogin2FARequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSessionLoginValidate(authLogin2FARequestDto: AuthLogin2FARequestDto, options?: any): AxiosPromise<BaseResponseLoginResponseDto> {
            return AuthControllerApiFp(configuration).authSessionLoginValidate(authLogin2FARequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary SAML Success
         * @param {object} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        azureCallback(request: object, options?: any): AxiosPromise<void> {
            return AuthControllerApiFp(configuration).azureCallback(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to revoke token
         * @param {LogoutRequestDto} logoutRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(logoutRequestDto: LogoutRequestDto, options?: any): AxiosPromise<BaseResponseLogoutResponseDto> {
            return AuthControllerApiFp(configuration).logout(logoutRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to check processor service is running
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ping(options?: any): AxiosPromise<BaseResponseString> {
            return AuthControllerApiFp(configuration).ping(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to validate token
         * @param {ValidateRequestDto} validateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validate(validateRequestDto: ValidateRequestDto, options?: any): AxiosPromise<BaseResponseValidateResponseDto> {
            return AuthControllerApiFp(configuration).validate(validateRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthControllerApi - object-oriented interface
 * @export
 * @class AuthControllerApi
 * @extends {BaseAPI}
 */
export class AuthControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to get token for application
     * @param {LoginRequestDto} loginRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthControllerApi
     */
    public authSessionLogin(loginRequestDto: LoginRequestDto, options?: any) {
        return AuthControllerApiFp(this.configuration).authSessionLogin(loginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to validate token for application
     * @param {AuthLogin2FARequestDto} authLogin2FARequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthControllerApi
     */
    public authSessionLoginValidate(authLogin2FARequestDto: AuthLogin2FARequestDto, options?: any) {
        return AuthControllerApiFp(this.configuration).authSessionLoginValidate(authLogin2FARequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary SAML Success
     * @param {object} request 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthControllerApi
     */
    public azureCallback(request: object, options?: any) {
        return AuthControllerApiFp(this.configuration).azureCallback(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to revoke token
     * @param {LogoutRequestDto} logoutRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthControllerApi
     */
    public logout(logoutRequestDto: LogoutRequestDto, options?: any) {
        return AuthControllerApiFp(this.configuration).logout(logoutRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to check processor service is running
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthControllerApi
     */
    public ping(options?: any) {
        return AuthControllerApiFp(this.configuration).ping(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to validate token
     * @param {ValidateRequestDto} validateRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthControllerApi
     */
    public validate(validateRequestDto: ValidateRequestDto, options?: any) {
        return AuthControllerApiFp(this.configuration).validate(validateRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * HomeControllerApi - axios parameter creator
 * @export
 */
export const HomeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeControllerApi - functional programming interface
 * @export
 */
export const HomeControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async index(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await HomeControllerApiAxiosParamCreator(configuration).index(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HomeControllerApi - factory interface
 * @export
 */
export const HomeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index(options?: any): AxiosPromise<BaseResponseString> {
            return HomeControllerApiFp(configuration).index(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeControllerApi - object-oriented interface
 * @export
 * @class HomeControllerApi
 * @extends {BaseAPI}
 */
export class HomeControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeControllerApi
     */
    public index(options?: any) {
        return HomeControllerApiFp(this.configuration).index(options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * OtpControllerApi - axios parameter creator
 * @export
 */
export const OtpControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to resend otp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendOtp: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/auth/otp/resend`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to check status otp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statusOtpUser: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/auth/otp/status`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to validate otp
         * @param {OtpRequestDto} otpRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateOtp: async (otpRequestDto: OtpRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'otpRequestDto' is not null or undefined
            if (otpRequestDto === null || otpRequestDto === undefined) {
                throw new RequiredError('otpRequestDto','Required parameter otpRequestDto was null or undefined when calling validateOtp.');
            }
            const localVarPath = `/v1/auth/otp/validate`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof otpRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(otpRequestDto !== undefined ? otpRequestDto : {}) : (otpRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OtpControllerApi - functional programming interface
 * @export
 */
export const OtpControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to resend otp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendOtp(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoBoolean>> {
            const localVarAxiosArgs = await OtpControllerApiAxiosParamCreator(configuration).resendOtp(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to check status otp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statusOtpUser(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoOtpResponseDto>> {
            const localVarAxiosArgs = await OtpControllerApiAxiosParamCreator(configuration).statusOtpUser(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to validate otp
         * @param {OtpRequestDto} otpRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateOtp(otpRequestDto: OtpRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoOtpResponseDto>> {
            const localVarAxiosArgs = await OtpControllerApiAxiosParamCreator(configuration).validateOtp(otpRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * OtpControllerApi - factory interface
 * @export
 */
export const OtpControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to resend otp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendOtp(options?: any): AxiosPromise<BaseResponseGenericSingleDtoBoolean> {
            return OtpControllerApiFp(configuration).resendOtp(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to check status otp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statusOtpUser(options?: any): AxiosPromise<BaseResponseGenericSingleDtoOtpResponseDto> {
            return OtpControllerApiFp(configuration).statusOtpUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to validate otp
         * @param {OtpRequestDto} otpRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateOtp(otpRequestDto: OtpRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoOtpResponseDto> {
            return OtpControllerApiFp(configuration).validateOtp(otpRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OtpControllerApi - object-oriented interface
 * @export
 * @class OtpControllerApi
 * @extends {BaseAPI}
 */
export class OtpControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to resend otp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OtpControllerApi
     */
    public resendOtp(options?: any) {
        return OtpControllerApiFp(this.configuration).resendOtp(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to check status otp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OtpControllerApi
     */
    public statusOtpUser(options?: any) {
        return OtpControllerApiFp(this.configuration).statusOtpUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to validate otp
     * @param {OtpRequestDto} otpRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OtpControllerApi
     */
    public validateOtp(otpRequestDto: OtpRequestDto, options?: any) {
        return OtpControllerApiFp(this.configuration).validateOtp(otpRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * V2AuthControllerApi - axios parameter creator
 * @export
 */
export const V2AuthControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get token for main application
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authCheck: async (loginRequestDto: LoginRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequestDto' is not null or undefined
            if (loginRequestDto === null || loginRequestDto === undefined) {
                throw new RequiredError('loginRequestDto','Required parameter loginRequestDto was null or undefined when calling authCheck.');
            }
            const localVarPath = `/v2/auth/validate`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof loginRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(loginRequestDto !== undefined ? loginRequestDto : {}) : (loginRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API create new password
         * @param {CreateNewPasswordRequest} createNewPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewPassword: async (createNewPasswordRequest: CreateNewPasswordRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'createNewPasswordRequest' is not null or undefined
            if (createNewPasswordRequest === null || createNewPasswordRequest === undefined) {
                throw new RequiredError('createNewPasswordRequest','Required parameter createNewPasswordRequest was null or undefined when calling createNewPassword.');
            }
            const localVarPath = `/v2/auth/create-password`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof createNewPasswordRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(createNewPasswordRequest !== undefined ? createNewPasswordRequest : {}) : (createNewPasswordRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API forgot password
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPassword: async (loginRequestDto: LoginRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequestDto' is not null or undefined
            if (loginRequestDto === null || loginRequestDto === undefined) {
                throw new RequiredError('loginRequestDto','Required parameter loginRequestDto was null or undefined when calling forgotPassword.');
            }
            const localVarPath = `/v2/auth/forgot-password`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof loginRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(loginRequestDto !== undefined ? loginRequestDto : {}) : (loginRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API profile user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profile: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/auth/profile`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * V2AuthControllerApi - functional programming interface
 * @export
 */
export const V2AuthControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get token for main application
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authCheck(loginRequestDto: LoginRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLoginResponseDto>> {
            const localVarAxiosArgs = await V2AuthControllerApiAxiosParamCreator(configuration).authCheck(loginRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API create new password
         * @param {CreateNewPasswordRequest} createNewPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewPassword(createNewPasswordRequest: CreateNewPasswordRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUserV2>> {
            const localVarAxiosArgs = await V2AuthControllerApiAxiosParamCreator(configuration).createNewPassword(createNewPasswordRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API forgot password
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forgotPassword(loginRequestDto: LoginRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await V2AuthControllerApiAxiosParamCreator(configuration).forgotPassword(loginRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API profile user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profile(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUserDetailv2Response>> {
            const localVarAxiosArgs = await V2AuthControllerApiAxiosParamCreator(configuration).profile(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * V2AuthControllerApi - factory interface
 * @export
 */
export const V2AuthControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to get token for main application
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authCheck(loginRequestDto: LoginRequestDto, options?: any): AxiosPromise<BaseResponseLoginResponseDto> {
            return V2AuthControllerApiFp(configuration).authCheck(loginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API create new password
         * @param {CreateNewPasswordRequest} createNewPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewPassword(createNewPasswordRequest: CreateNewPasswordRequest, options?: any): AxiosPromise<BaseResponseUserV2> {
            return V2AuthControllerApiFp(configuration).createNewPassword(createNewPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API forgot password
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPassword(loginRequestDto: LoginRequestDto, options?: any): AxiosPromise<BaseResponseString> {
            return V2AuthControllerApiFp(configuration).forgotPassword(loginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API profile user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profile(options?: any): AxiosPromise<BaseResponseUserDetailv2Response> {
            return V2AuthControllerApiFp(configuration).profile(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * V2AuthControllerApi - object-oriented interface
 * @export
 * @class V2AuthControllerApi
 * @extends {BaseAPI}
 */
export class V2AuthControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to get token for main application
     * @param {LoginRequestDto} loginRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2AuthControllerApi
     */
    public authCheck(loginRequestDto: LoginRequestDto, options?: any) {
        return V2AuthControllerApiFp(this.configuration).authCheck(loginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API create new password
     * @param {CreateNewPasswordRequest} createNewPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2AuthControllerApi
     */
    public createNewPassword(createNewPasswordRequest: CreateNewPasswordRequest, options?: any) {
        return V2AuthControllerApiFp(this.configuration).createNewPassword(createNewPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API forgot password
     * @param {LoginRequestDto} loginRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2AuthControllerApi
     */
    public forgotPassword(loginRequestDto: LoginRequestDto, options?: any) {
        return V2AuthControllerApiFp(this.configuration).forgotPassword(loginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API profile user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2AuthControllerApi
     */
    public profile(options?: any) {
        return V2AuthControllerApiFp(this.configuration).profile(options).then((request) => request(this.axios, this.basePath));
    }

}


