import type { ApprovalListResponse } from '../ApprovalList/ApprovalList.types';


export const mockApprovalData: ApprovalListResponse = {
  data: {
    contents: [
      {
        aging: '30',
        bucketProcessId: 'MON-001',
        createdAt: '2025-10-01T09:00:00.000+07:00',
        division: 'IT',
        divisionId: 'DIV001',
        kadivApprovedBy: null,
        kadivApprovedate: null,
        modifiedAt: '2025-10-05T14:30:00.000+07:00',
        modifiedBy: 'Admin System',
        remarks: 'Perubahan struktur organisasi',
        staffDivision: 'Manager',
        staffDivisionLabel: 'Manager',
        staffId: 'USR001',
        staffName: 'John Doe',
        status: 'ACTIVE',
        statusLabel: 'Active',
        tlApprovedBy: 'IT Manager',
        tlApprovedate: '2025-10-05T15:45:00.000+07:00',
      },
      {
        aging: '60',
        bucketProcessId: 'MON-002',
        createdAt: '2025-09-28T10:30:00.000+07:00',
        division: 'HR',
        divisionId: 'DIV002',
        kadivApprovedBy: 'Head of HR',
        kadivApprovedate: '2025-10-04T13:15:00.000+07:00',
        modifiedAt: '2025-10-04T11:20:00.000+07:00',
        modifiedBy: 'HR Department',
        remarks: 'Rotasi pekerjaan',
        staffDivision: 'Supervisor',
        staffDivisionLabel: 'Supervisor',
        staffId: 'USR002',
        staffName: 'Jane Smith',
        status: 'INACTIVE',
        statusLabel: 'Inactive',
        tlApprovedBy: null,
        tlApprovedate: null,
      },
      {
        aging: '90',
        bucketProcessId: 'MON-003',
        createdAt: '2025-09-25T08:15:00.000+07:00',
        division: 'Finance',
        divisionId: 'DIV003',
        kadivApprovedBy: 'Finance Director',
        kadivApprovedate: '2025-10-03T17:30:00.000+07:00',
        modifiedAt: '2025-10-03T16:45:00.000+07:00',
        modifiedBy: 'System Admin',
        remarks: 'Project based assignment',
        staffDivision: 'Staff',
        staffDivisionLabel: 'Staff',
        staffId: 'USR003',
        staffName: 'Bob Johnson',
        status: 'ACTIVE',
        statusLabel: 'Active',
        tlApprovedBy: null,
        tlApprovedate: null,
      },
    ],
    page: {
      itemPerPage: 10,
      noPage: 1,
      totalData: 3,
      totalPage: 1,
    },
  },
  errorCode: '0000',
  errorDesc: 'Success',
  errorDetail: null,
  errorSource: 'approval-service',
  operationId: null,
  timestamp: '06-10-2025 06:23:07',
};
