export const mockLimitAnak = {
  aliasFasilitasAnak: 'Eweuh',
  availableMarker: 'Teuing',
  baruPerpanjangan: 'Teuing',
  cabangPembukaanLimit: 'Teuing',
  catatan1: 'Teuing',
  cifKelompok: 'Teuing',
  countryOfRisk: 'Teuing',
  countryPercent: 'Teuing',
  datiLokasiProyek: 'Teuing',
  frekuensiReview: 'Teuing',
  golonganKredit: 'Teuing',
  jenisPenggunaan: 'Teuing',
  keteranganBmpp: 'Teuing',
  liabilityNumber: 'Teuing',
  limitId: 'Lim-123',
  maksimalPenggunaan: '1000000',
  mataUangLimit: 'Rupiah',
  nilaiFasilitasOnline: 'Teuing',
  nilaiKelonggaranTarik: 'Teuing',
  nominalFasilitasLimit: '1000000',
  onlineUpdate: 'Teuing',
  orientasiPenggunaan: 'Teuing',
  penandaBmpk: 'Teuing',
  pipelineId: 'Pipe-123',
  sebelumRestrukturisasiPlafon: 'Teuing',
  sifatPiutang: 'Teuing',
  tanggalAP: '21 Aug 2025',
  tanggalBerakhir: '21 Aug 2026',
  tanggalBerlaku: '21 Aug 2025',
  tanggalInputLimit: '21 Aug 2025',
  totalOutstanding: 'Teuing',
  tracerId: 'Pipe-123',
};
