export const modal = {
  DEBTOR: 'DEBTOR',
  MODAL_TABLE_DK: 'MODAL_TABLE_DK',

};
export const CREDIT_CHECKING_RESULT = 'CREDIT_CHECKING_RESULT';
export const CREDIT_CHECKING_MODULE = 'CREDIT_CHECKING';
