// tslint:disable
/**
 * OpenAPI Draft Memo Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AttachmentRequest
 */
export interface AttachmentRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof AttachmentRequest
     */
    digitalMemo?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof AttachmentRequest
     */
    financingDocument?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof AttachmentRequest
     */
    supportingDocument?: Array<number>;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericBucketResponseDtoDraftMemoResponseDto
 */
export interface BaseResponseGenericBucketResponseDtoDraftMemoResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoDraftMemoResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoDraftMemoResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoDraftMemoResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoDraftMemoResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericBucketResponseDtoDraftMemoResponseDto}
     * @memberof BaseResponseGenericBucketResponseDtoDraftMemoResponseDto
     */
    data?: GenericBucketResponseDtoDraftMemoResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto
 */
export interface BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericBucketResponseDtoListProposalAttachmentResponseDto}
     * @memberof BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    data?: GenericBucketResponseDtoListProposalAttachmentResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto
 */
export interface BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericSingleDtoDraftMemoGenerateResponseDto}
     * @memberof BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto
     */
    data?: GenericSingleDtoDraftMemoGenerateResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoDraftMemoResponseDto
 */
export interface BaseResponseGenericSingleDtoDraftMemoResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDraftMemoResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericSingleDtoDraftMemoResponseDto}
     * @memberof BaseResponseGenericSingleDtoDraftMemoResponseDto
     */
    data?: GenericSingleDtoDraftMemoResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoProposalAttachmentResponseDto
 */
export interface BaseResponseGenericSingleDtoProposalAttachmentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalAttachmentResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalAttachmentResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalAttachmentResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalAttachmentResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericSingleDtoProposalAttachmentResponseDto}
     * @memberof BaseResponseGenericSingleDtoProposalAttachmentResponseDto
     */
    data?: GenericSingleDtoProposalAttachmentResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoProposalResponseDto
 */
export interface BaseResponseGenericSingleDtoProposalResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoProposalResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericSingleDtoProposalResponseDto}
     * @memberof BaseResponseGenericSingleDtoProposalResponseDto
     */
    data?: GenericSingleDtoProposalResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoResponseByIdDtoLong
 */
export interface BaseResponseGenericSingleDtoResponseByIdDtoLong {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoResponseByIdDtoLong
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoResponseByIdDtoLong
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoResponseByIdDtoLong
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoResponseByIdDtoLong
     */
    errorDetail?: string;
    /**
     * 
     * @type {GenericSingleDtoResponseByIdDtoLong}
     * @memberof BaseResponseGenericSingleDtoResponseByIdDtoLong
     */
    data?: GenericSingleDtoResponseByIdDtoLong;
}
/**
 * 
 * @export
 * @interface BaseResponseProposalActionsResponseDto
 */
export interface BaseResponseProposalActionsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseProposalActionsResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseProposalActionsResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseProposalActionsResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseProposalActionsResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {ProposalActionsResponseDto}
     * @memberof BaseResponseProposalActionsResponseDto
     */
    data?: ProposalActionsResponseDto;
}
/**
 * 
 * @export
 * @interface DraftMemoGenerateResponseDto
 */
export interface DraftMemoGenerateResponseDto {
    /**
     * 
     * @type {string}
     * @memberof DraftMemoGenerateResponseDto
     */
    message?: string;
}
/**
 * 
 * @export
 * @interface DraftMemoRequest
 */
export interface DraftMemoRequest {
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequest
     */
    base64?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequest
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequest
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequest
     */
    formatGenerate?: string;
    /**
     * 
     * @type {number}
     * @memberof DraftMemoRequest
     */
    dratMemoId?: number;
}
/**
 * 
 * @export
 * @interface DraftMemoRequestSave
 */
export interface DraftMemoRequestSave {
    /**
     * 
     * @type {number}
     * @memberof DraftMemoRequestSave
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequestSave
     */
    file?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequestSave
     */
    documentDate?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequestSave
     */
    documentName?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequestSave
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoRequestSave
     */
    fileExtension?: string;
}
/**
 * 
 * @export
 * @interface DraftMemoResponseDto
 */
export interface DraftMemoResponseDto {
    /**
     * 
     * @type {number}
     * @memberof DraftMemoResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    documentType?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    documentName?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    fileUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    documentNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    fileExtension?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    createdBy?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DraftMemoResponseDto
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    documentDate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DraftMemoResponseDto
     */
    viewOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DraftMemoResponseDto
     */
    isGenerate?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DraftMemoResponseDto
     */
    type?: string;
}
/**
 * 
 * @export
 * @interface GenericBucketRequestDtoDraftMemoRequest
 */
export interface GenericBucketRequestDtoDraftMemoRequest {
    /**
     * 
     * @type {PageRequestDto}
     * @memberof GenericBucketRequestDtoDraftMemoRequest
     */
    page?: PageRequestDto;
    /**
     * 
     * @type {SortRequestDto}
     * @memberof GenericBucketRequestDtoDraftMemoRequest
     */
    sortList?: SortRequestDto;
    /**
     * 
     * @type {SearchDetailRequestDto}
     * @memberof GenericBucketRequestDtoDraftMemoRequest
     */
    searchDetail?: SearchDetailRequestDto;
    /**
     * 
     * @type {DraftMemoRequest}
     * @memberof GenericBucketRequestDtoDraftMemoRequest
     */
    filter?: DraftMemoRequest;
}
/**
 * 
 * @export
 * @interface GenericBucketRequestDtoListProposalAttachmentRequestDto
 */
export interface GenericBucketRequestDtoListProposalAttachmentRequestDto {
    /**
     * 
     * @type {PageRequestDto}
     * @memberof GenericBucketRequestDtoListProposalAttachmentRequestDto
     */
    page?: PageRequestDto;
    /**
     * 
     * @type {SortRequestDto}
     * @memberof GenericBucketRequestDtoListProposalAttachmentRequestDto
     */
    sortList?: SortRequestDto;
    /**
     * 
     * @type {SearchDetailRequestDto}
     * @memberof GenericBucketRequestDtoListProposalAttachmentRequestDto
     */
    searchDetail?: SearchDetailRequestDto;
    /**
     * 
     * @type {ListProposalAttachmentRequestDto}
     * @memberof GenericBucketRequestDtoListProposalAttachmentRequestDto
     */
    filter?: ListProposalAttachmentRequestDto;
}
/**
 * 
 * @export
 * @interface GenericBucketResponseDtoDraftMemoResponseDto
 */
export interface GenericBucketResponseDtoDraftMemoResponseDto {
    /**
     * 
     * @type {Array<DraftMemoResponseDto>}
     * @memberof GenericBucketResponseDtoDraftMemoResponseDto
     */
    contents?: Array<DraftMemoResponseDto>;
    /**
     * 
     * @type {PageResponseDto}
     * @memberof GenericBucketResponseDtoDraftMemoResponseDto
     */
    page?: PageResponseDto;
}
/**
 * 
 * @export
 * @interface GenericBucketResponseDtoListProposalAttachmentResponseDto
 */
export interface GenericBucketResponseDtoListProposalAttachmentResponseDto {
    /**
     * 
     * @type {Array<ListProposalAttachmentResponseDto>}
     * @memberof GenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    contents?: Array<ListProposalAttachmentResponseDto>;
    /**
     * 
     * @type {PageResponseDto}
     * @memberof GenericBucketResponseDtoListProposalAttachmentResponseDto
     */
    page?: PageResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoDraftMemoGenerateResponseDto
 */
export interface GenericSingleDtoDraftMemoGenerateResponseDto {
    /**
     * 
     * @type {DraftMemoGenerateResponseDto}
     * @memberof GenericSingleDtoDraftMemoGenerateResponseDto
     */
    content?: DraftMemoGenerateResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoDraftMemoResponseDto
 */
export interface GenericSingleDtoDraftMemoResponseDto {
    /**
     * 
     * @type {DraftMemoResponseDto}
     * @memberof GenericSingleDtoDraftMemoResponseDto
     */
    content?: DraftMemoResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoProposalAttachmentResponseDto
 */
export interface GenericSingleDtoProposalAttachmentResponseDto {
    /**
     * 
     * @type {ProposalAttachmentResponseDto}
     * @memberof GenericSingleDtoProposalAttachmentResponseDto
     */
    content?: ProposalAttachmentResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoProposalResponseDto
 */
export interface GenericSingleDtoProposalResponseDto {
    /**
     * 
     * @type {ProposalResponseDto}
     * @memberof GenericSingleDtoProposalResponseDto
     */
    content?: ProposalResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoResponseByIdDtoLong
 */
export interface GenericSingleDtoResponseByIdDtoLong {
    /**
     * 
     * @type {ResponseByIdDtoLong}
     * @memberof GenericSingleDtoResponseByIdDtoLong
     */
    content?: ResponseByIdDtoLong;
}
/**
 * 
 * @export
 * @interface ListProposalAttachmentRequestDto
 */
export interface ListProposalAttachmentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentRequestDto
     */
    documentGroup?: string;
}
/**
 * 
 * @export
 * @interface ListProposalAttachmentResponseDto
 */
export interface ListProposalAttachmentResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ListProposalAttachmentResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentGroup?: ListProposalAttachmentResponseDtoDocumentGroupEnum;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentType?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentTypeLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentExtension?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    document?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentName?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    documentDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    ownership?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    modifiedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    modifiedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ListProposalAttachmentResponseDto
     */
    debtorId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListProposalAttachmentResponseDto
     */
    viewOnly?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum ListProposalAttachmentResponseDtoDocumentGroupEnum {
    DIGITALMEMO = 'DIGITAL_MEMO',
    FINANCINGDOCUMENT = 'FINANCING_DOCUMENT',
    SUPPORTINGDOCUMENT = 'SUPPORTING_DOCUMENT'
}

/**
 * 
 * @export
 * @interface PageRequestDto
 */
export interface PageRequestDto {
    /**
     * 
     * @type {number}
     * @memberof PageRequestDto
     */
    noPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRequestDto
     */
    itemPerPage?: number;
}
/**
 * 
 * @export
 * @interface PageResponseDto
 */
export interface PageResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    noPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    itemPerPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    totalPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    totalData?: number;
}
/**
 * 
 * @export
 * @interface ProposalActionsRequestDto
 */
export interface ProposalActionsRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ProposalActionsRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalActionsRequestDto
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalActionsRequestDto
     */
    status?: string;
}
/**
 * 
 * @export
 * @interface ProposalActionsResponseDto
 */
export interface ProposalActionsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ProposalActionsResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalActionsResponseDto
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalActionsResponseDto
     */
    status?: string;
}
/**
 * 
 * @export
 * @interface ProposalAttachmentRequestDto
 */
export interface ProposalAttachmentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ProposalAttachmentRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalAttachmentRequestDto
     */
    documentGroup?: ProposalAttachmentRequestDtoDocumentGroupEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProposalAttachmentRequestDto
     */
    attachments?: Array<number>;
}

/**
    * @export
    * @enum {string}
    */
export enum ProposalAttachmentRequestDtoDocumentGroupEnum {
    DIGITALMEMO = 'DIGITAL_MEMO',
    FINANCINGDOCUMENT = 'FINANCING_DOCUMENT',
    SUPPORTINGDOCUMENT = 'SUPPORTING_DOCUMENT'
}

/**
 * 
 * @export
 * @interface ProposalAttachmentResponseDto
 */
export interface ProposalAttachmentResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ProposalAttachmentResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProposalAttachmentResponseDto
     */
    bucketProcessId?: string;
}
/**
 * 
 * @export
 * @interface ProposalRequestDto
 */
export interface ProposalRequestDto {
    /**
     * 
     * @type {number}
     * @memberof ProposalRequestDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProposalRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {any}
     * @memberof ProposalRequestDto
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof ProposalRequestDto
     */
    title?: string;
}
/**
 * 
 * @export
 * @interface ProposalResponseDto
 */
export interface ProposalResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ProposalResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProposalResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalResponseDto
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProposalResponseDto
     */
    viewOnly?: boolean;
}
/**
 * 
 * @export
 * @interface ProposalSubmitRequestDto
 */
export interface ProposalSubmitRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ProposalSubmitRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalSubmitRequestDto
     */
    comment?: string;
    /**
     * 
     * @type {AttachmentRequest}
     * @memberof ProposalSubmitRequestDto
     */
    attachment?: AttachmentRequest;
}
/**
 * 
 * @export
 * @interface RequestByBucketProcessIdDto
 */
export interface RequestByBucketProcessIdDto {
    /**
     * 
     * @type {string}
     * @memberof RequestByBucketProcessIdDto
     */
    bucketProcessId?: string;
}
/**
 * 
 * @export
 * @interface RequestByIdDtoLong
 */
export interface RequestByIdDtoLong {
    /**
     * 
     * @type {number}
     * @memberof RequestByIdDtoLong
     */
    id?: number;
}
/**
 * 
 * @export
 * @interface ResponseByIdDtoLong
 */
export interface ResponseByIdDtoLong {
    /**
     * 
     * @type {number}
     * @memberof ResponseByIdDtoLong
     */
    id?: number;
}
/**
 * 
 * @export
 * @interface SearchDetailRequestDto
 */
export interface SearchDetailRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SearchDetailRequestDto
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchDetailRequestDto
     */
    value?: string;
}
/**
 * 
 * @export
 * @interface SortRequestDto
 */
export interface SortRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SortRequestDto
     */
    columnName?: string;
    /**
     * 
     * @type {string}
     * @memberof SortRequestDto
     */
    sortType?: string;
}

/**
 * DraftMemoControllerApi - axios parameter creator
 * @export
 */
export const DraftMemoControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to delete draft memo from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDraftMemo: async (requestByIdDtoLong: RequestByIdDtoLong, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestByIdDtoLong' is not null or undefined
            if (requestByIdDtoLong === null || requestByIdDtoLong === undefined) {
                throw new RequiredError('requestByIdDtoLong','Required parameter requestByIdDtoLong was null or undefined when calling deleteDraftMemo.');
            }
            const localVarPath = `/v1/draft-memo/delete`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof requestByIdDtoLong !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(requestByIdDtoLong !== undefined ? requestByIdDtoLong : {}) : (requestByIdDtoLong || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to generate PDF draft memo
         * @param {DraftMemoRequest} draftMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePdfDraftMemo: async (draftMemoRequest: DraftMemoRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'draftMemoRequest' is not null or undefined
            if (draftMemoRequest === null || draftMemoRequest === undefined) {
                throw new RequiredError('draftMemoRequest','Required parameter draftMemoRequest was null or undefined when calling generatePdfDraftMemo.');
            }
            const localVarPath = `/v1/draft-memo/generate`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof draftMemoRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(draftMemoRequest !== undefined ? draftMemoRequest : {}) : (draftMemoRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get draft memo by id from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftMemoById: async (requestByIdDtoLong: RequestByIdDtoLong, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestByIdDtoLong' is not null or undefined
            if (requestByIdDtoLong === null || requestByIdDtoLong === undefined) {
                throw new RequiredError('requestByIdDtoLong','Required parameter requestByIdDtoLong was null or undefined when calling getDraftMemoById.');
            }
            const localVarPath = `/v1/draft-memo/get-by-id`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof requestByIdDtoLong !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(requestByIdDtoLong !== undefined ? requestByIdDtoLong : {}) : (requestByIdDtoLong || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get draft memo history from database
         * @param {GenericBucketRequestDtoDraftMemoRequest} genericBucketRequestDtoDraftMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftMemoHistory: async (genericBucketRequestDtoDraftMemoRequest: GenericBucketRequestDtoDraftMemoRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genericBucketRequestDtoDraftMemoRequest' is not null or undefined
            if (genericBucketRequestDtoDraftMemoRequest === null || genericBucketRequestDtoDraftMemoRequest === undefined) {
                throw new RequiredError('genericBucketRequestDtoDraftMemoRequest','Required parameter genericBucketRequestDtoDraftMemoRequest was null or undefined when calling getDraftMemoHistory.');
            }
            const localVarPath = `/v1/draft-memo/history`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof genericBucketRequestDtoDraftMemoRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(genericBucketRequestDtoDraftMemoRequest !== undefined ? genericBucketRequestDtoDraftMemoRequest : {}) : (genericBucketRequestDtoDraftMemoRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to save draft memo
         * @param {DraftMemoRequestSave} draftMemoRequestSave 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveDraftMemo: async (draftMemoRequestSave: DraftMemoRequestSave, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'draftMemoRequestSave' is not null or undefined
            if (draftMemoRequestSave === null || draftMemoRequestSave === undefined) {
                throw new RequiredError('draftMemoRequestSave','Required parameter draftMemoRequestSave was null or undefined when calling saveDraftMemo.');
            }
            const localVarPath = `/v1/draft-memo/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof draftMemoRequestSave !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(draftMemoRequestSave !== undefined ? draftMemoRequestSave : {}) : (draftMemoRequestSave || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DraftMemoControllerApi - functional programming interface
 * @export
 */
export const DraftMemoControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to delete draft memo from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDraftMemo(requestByIdDtoLong: RequestByIdDtoLong, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoResponseByIdDtoLong>> {
            const localVarAxiosArgs = await DraftMemoControllerApiAxiosParamCreator(configuration).deleteDraftMemo(requestByIdDtoLong, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to generate PDF draft memo
         * @param {DraftMemoRequest} draftMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generatePdfDraftMemo(draftMemoRequest: DraftMemoRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto>> {
            const localVarAxiosArgs = await DraftMemoControllerApiAxiosParamCreator(configuration).generatePdfDraftMemo(draftMemoRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get draft memo by id from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraftMemoById(requestByIdDtoLong: RequestByIdDtoLong, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoDraftMemoResponseDto>> {
            const localVarAxiosArgs = await DraftMemoControllerApiAxiosParamCreator(configuration).getDraftMemoById(requestByIdDtoLong, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get draft memo history from database
         * @param {GenericBucketRequestDtoDraftMemoRequest} genericBucketRequestDtoDraftMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraftMemoHistory(genericBucketRequestDtoDraftMemoRequest: GenericBucketRequestDtoDraftMemoRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericBucketResponseDtoDraftMemoResponseDto>> {
            const localVarAxiosArgs = await DraftMemoControllerApiAxiosParamCreator(configuration).getDraftMemoHistory(genericBucketRequestDtoDraftMemoRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to save draft memo
         * @param {DraftMemoRequestSave} draftMemoRequestSave 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveDraftMemo(draftMemoRequestSave: DraftMemoRequestSave, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto>> {
            const localVarAxiosArgs = await DraftMemoControllerApiAxiosParamCreator(configuration).saveDraftMemo(draftMemoRequestSave, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DraftMemoControllerApi - factory interface
 * @export
 */
export const DraftMemoControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to delete draft memo from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDraftMemo(requestByIdDtoLong: RequestByIdDtoLong, options?: any): AxiosPromise<BaseResponseGenericSingleDtoResponseByIdDtoLong> {
            return DraftMemoControllerApiFp(configuration).deleteDraftMemo(requestByIdDtoLong, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to generate PDF draft memo
         * @param {DraftMemoRequest} draftMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePdfDraftMemo(draftMemoRequest: DraftMemoRequest, options?: any): AxiosPromise<BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto> {
            return DraftMemoControllerApiFp(configuration).generatePdfDraftMemo(draftMemoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get draft memo by id from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftMemoById(requestByIdDtoLong: RequestByIdDtoLong, options?: any): AxiosPromise<BaseResponseGenericSingleDtoDraftMemoResponseDto> {
            return DraftMemoControllerApiFp(configuration).getDraftMemoById(requestByIdDtoLong, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get draft memo history from database
         * @param {GenericBucketRequestDtoDraftMemoRequest} genericBucketRequestDtoDraftMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftMemoHistory(genericBucketRequestDtoDraftMemoRequest: GenericBucketRequestDtoDraftMemoRequest, options?: any): AxiosPromise<BaseResponseGenericBucketResponseDtoDraftMemoResponseDto> {
            return DraftMemoControllerApiFp(configuration).getDraftMemoHistory(genericBucketRequestDtoDraftMemoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to save draft memo
         * @param {DraftMemoRequestSave} draftMemoRequestSave 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveDraftMemo(draftMemoRequestSave: DraftMemoRequestSave, options?: any): AxiosPromise<BaseResponseGenericSingleDtoDraftMemoGenerateResponseDto> {
            return DraftMemoControllerApiFp(configuration).saveDraftMemo(draftMemoRequestSave, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DraftMemoControllerApi - object-oriented interface
 * @export
 * @class DraftMemoControllerApi
 * @extends {BaseAPI}
 */
export class DraftMemoControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to delete draft memo from database
     * @param {RequestByIdDtoLong} requestByIdDtoLong 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftMemoControllerApi
     */
    public deleteDraftMemo(requestByIdDtoLong: RequestByIdDtoLong, options?: any) {
        return DraftMemoControllerApiFp(this.configuration).deleteDraftMemo(requestByIdDtoLong, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to generate PDF draft memo
     * @param {DraftMemoRequest} draftMemoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftMemoControllerApi
     */
    public generatePdfDraftMemo(draftMemoRequest: DraftMemoRequest, options?: any) {
        return DraftMemoControllerApiFp(this.configuration).generatePdfDraftMemo(draftMemoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get draft memo by id from database
     * @param {RequestByIdDtoLong} requestByIdDtoLong 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftMemoControllerApi
     */
    public getDraftMemoById(requestByIdDtoLong: RequestByIdDtoLong, options?: any) {
        return DraftMemoControllerApiFp(this.configuration).getDraftMemoById(requestByIdDtoLong, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get draft memo history from database
     * @param {GenericBucketRequestDtoDraftMemoRequest} genericBucketRequestDtoDraftMemoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftMemoControllerApi
     */
    public getDraftMemoHistory(genericBucketRequestDtoDraftMemoRequest: GenericBucketRequestDtoDraftMemoRequest, options?: any) {
        return DraftMemoControllerApiFp(this.configuration).getDraftMemoHistory(genericBucketRequestDtoDraftMemoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to save draft memo
     * @param {DraftMemoRequestSave} draftMemoRequestSave 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftMemoControllerApi
     */
    public saveDraftMemo(draftMemoRequestSave: DraftMemoRequestSave, options?: any) {
        return DraftMemoControllerApiFp(this.configuration).saveDraftMemo(draftMemoRequestSave, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * ProposalAttachmentControllerApi - axios parameter creator
 * @export
 */
export const ProposalAttachmentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to delete proposal attachment modify from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProposalAttachment: async (requestByIdDtoLong: RequestByIdDtoLong, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestByIdDtoLong' is not null or undefined
            if (requestByIdDtoLong === null || requestByIdDtoLong === undefined) {
                throw new RequiredError('requestByIdDtoLong','Required parameter requestByIdDtoLong was null or undefined when calling deleteProposalAttachment.');
            }
            const localVarPath = `/v1/proposal/attachment/delete`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof requestByIdDtoLong !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(requestByIdDtoLong !== undefined ? requestByIdDtoLong : {}) : (requestByIdDtoLong || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API get List Proposal Attachment from database
         * @param {GenericBucketRequestDtoListProposalAttachmentRequestDto} genericBucketRequestDtoListProposalAttachmentRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListProposalAttachment: async (genericBucketRequestDtoListProposalAttachmentRequestDto: GenericBucketRequestDtoListProposalAttachmentRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genericBucketRequestDtoListProposalAttachmentRequestDto' is not null or undefined
            if (genericBucketRequestDtoListProposalAttachmentRequestDto === null || genericBucketRequestDtoListProposalAttachmentRequestDto === undefined) {
                throw new RequiredError('genericBucketRequestDtoListProposalAttachmentRequestDto','Required parameter genericBucketRequestDtoListProposalAttachmentRequestDto was null or undefined when calling getListProposalAttachment.');
            }
            const localVarPath = `/v1/proposal/attachment/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof genericBucketRequestDtoListProposalAttachmentRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(genericBucketRequestDtoListProposalAttachmentRequestDto !== undefined ? genericBucketRequestDtoListProposalAttachmentRequestDto : {}) : (genericBucketRequestDtoListProposalAttachmentRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to submit proposal attachment modify from database
         * @param {ProposalAttachmentRequestDto} proposalAttachmentRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitProposalAttachmentModify: async (proposalAttachmentRequestDto: ProposalAttachmentRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'proposalAttachmentRequestDto' is not null or undefined
            if (proposalAttachmentRequestDto === null || proposalAttachmentRequestDto === undefined) {
                throw new RequiredError('proposalAttachmentRequestDto','Required parameter proposalAttachmentRequestDto was null or undefined when calling submitProposalAttachmentModify.');
            }
            const localVarPath = `/v1/proposal/attachment`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof proposalAttachmentRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(proposalAttachmentRequestDto !== undefined ? proposalAttachmentRequestDto : {}) : (proposalAttachmentRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProposalAttachmentControllerApi - functional programming interface
 * @export
 */
export const ProposalAttachmentControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to delete proposal attachment modify from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProposalAttachment(requestByIdDtoLong: RequestByIdDtoLong, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoProposalAttachmentResponseDto>> {
            const localVarAxiosArgs = await ProposalAttachmentControllerApiAxiosParamCreator(configuration).deleteProposalAttachment(requestByIdDtoLong, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API get List Proposal Attachment from database
         * @param {GenericBucketRequestDtoListProposalAttachmentRequestDto} genericBucketRequestDtoListProposalAttachmentRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListProposalAttachment(genericBucketRequestDtoListProposalAttachmentRequestDto: GenericBucketRequestDtoListProposalAttachmentRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto>> {
            const localVarAxiosArgs = await ProposalAttachmentControllerApiAxiosParamCreator(configuration).getListProposalAttachment(genericBucketRequestDtoListProposalAttachmentRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to submit proposal attachment modify from database
         * @param {ProposalAttachmentRequestDto} proposalAttachmentRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitProposalAttachmentModify(proposalAttachmentRequestDto: ProposalAttachmentRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoProposalAttachmentResponseDto>> {
            const localVarAxiosArgs = await ProposalAttachmentControllerApiAxiosParamCreator(configuration).submitProposalAttachmentModify(proposalAttachmentRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProposalAttachmentControllerApi - factory interface
 * @export
 */
export const ProposalAttachmentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to delete proposal attachment modify from database
         * @param {RequestByIdDtoLong} requestByIdDtoLong 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProposalAttachment(requestByIdDtoLong: RequestByIdDtoLong, options?: any): AxiosPromise<BaseResponseGenericSingleDtoProposalAttachmentResponseDto> {
            return ProposalAttachmentControllerApiFp(configuration).deleteProposalAttachment(requestByIdDtoLong, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API get List Proposal Attachment from database
         * @param {GenericBucketRequestDtoListProposalAttachmentRequestDto} genericBucketRequestDtoListProposalAttachmentRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListProposalAttachment(genericBucketRequestDtoListProposalAttachmentRequestDto: GenericBucketRequestDtoListProposalAttachmentRequestDto, options?: any): AxiosPromise<BaseResponseGenericBucketResponseDtoListProposalAttachmentResponseDto> {
            return ProposalAttachmentControllerApiFp(configuration).getListProposalAttachment(genericBucketRequestDtoListProposalAttachmentRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to submit proposal attachment modify from database
         * @param {ProposalAttachmentRequestDto} proposalAttachmentRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitProposalAttachmentModify(proposalAttachmentRequestDto: ProposalAttachmentRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoProposalAttachmentResponseDto> {
            return ProposalAttachmentControllerApiFp(configuration).submitProposalAttachmentModify(proposalAttachmentRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProposalAttachmentControllerApi - object-oriented interface
 * @export
 * @class ProposalAttachmentControllerApi
 * @extends {BaseAPI}
 */
export class ProposalAttachmentControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to delete proposal attachment modify from database
     * @param {RequestByIdDtoLong} requestByIdDtoLong 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalAttachmentControllerApi
     */
    public deleteProposalAttachment(requestByIdDtoLong: RequestByIdDtoLong, options?: any) {
        return ProposalAttachmentControllerApiFp(this.configuration).deleteProposalAttachment(requestByIdDtoLong, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API get List Proposal Attachment from database
     * @param {GenericBucketRequestDtoListProposalAttachmentRequestDto} genericBucketRequestDtoListProposalAttachmentRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalAttachmentControllerApi
     */
    public getListProposalAttachment(genericBucketRequestDtoListProposalAttachmentRequestDto: GenericBucketRequestDtoListProposalAttachmentRequestDto, options?: any) {
        return ProposalAttachmentControllerApiFp(this.configuration).getListProposalAttachment(genericBucketRequestDtoListProposalAttachmentRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to submit proposal attachment modify from database
     * @param {ProposalAttachmentRequestDto} proposalAttachmentRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalAttachmentControllerApi
     */
    public submitProposalAttachmentModify(proposalAttachmentRequestDto: ProposalAttachmentRequestDto, options?: any) {
        return ProposalAttachmentControllerApiFp(this.configuration).submitProposalAttachmentModify(proposalAttachmentRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * ProposalControllerApi - axios parameter creator
 * @export
 */
export const ProposalControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to decline proposal from database
         * @param {ProposalActionsRequestDto} proposalActionsRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        declineProposal: async (proposalActionsRequestDto: ProposalActionsRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'proposalActionsRequestDto' is not null or undefined
            if (proposalActionsRequestDto === null || proposalActionsRequestDto === undefined) {
                throw new RequiredError('proposalActionsRequestDto','Required parameter proposalActionsRequestDto was null or undefined when calling declineProposal.');
            }
            const localVarPath = `/v1/proposal/decline`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof proposalActionsRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(proposalActionsRequestDto !== undefined ? proposalActionsRequestDto : {}) : (proposalActionsRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get Proposal by bucket process id from database
         * @param {RequestByBucketProcessIdDto} requestByBucketProcessIdDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetailProposal: async (requestByBucketProcessIdDto: RequestByBucketProcessIdDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestByBucketProcessIdDto' is not null or undefined
            if (requestByBucketProcessIdDto === null || requestByBucketProcessIdDto === undefined) {
                throw new RequiredError('requestByBucketProcessIdDto','Required parameter requestByBucketProcessIdDto was null or undefined when calling getDetailProposal.');
            }
            const localVarPath = `/v1/proposal/detail`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof requestByBucketProcessIdDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(requestByBucketProcessIdDto !== undefined ? requestByBucketProcessIdDto : {}) : (requestByBucketProcessIdDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to Save Proposal to database
         * @param {number} [id] 
         * @param {string} [bucketProcessId] 
         * @param {any} [description] 
         * @param {string} [title] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProposal: async (id?: number, bucketProcessId?: string, description?: any, title?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/proposal/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();


            if (id !== undefined) { 
                localVarFormParams.append('id', id as any);
            }
    
            if (bucketProcessId !== undefined) { 
                localVarFormParams.append('bucketProcessId', bucketProcessId as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (title !== undefined) { 
                localVarFormParams.append('title', title as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to submit proposal from database
         * @param {ProposalSubmitRequestDto} proposalSubmitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitPipeline: async (proposalSubmitRequestDto: ProposalSubmitRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'proposalSubmitRequestDto' is not null or undefined
            if (proposalSubmitRequestDto === null || proposalSubmitRequestDto === undefined) {
                throw new RequiredError('proposalSubmitRequestDto','Required parameter proposalSubmitRequestDto was null or undefined when calling submitPipeline.');
            }
            const localVarPath = `/v1/proposal/submit`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof proposalSubmitRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(proposalSubmitRequestDto !== undefined ? proposalSubmitRequestDto : {}) : (proposalSubmitRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProposalControllerApi - functional programming interface
 * @export
 */
export const ProposalControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to decline proposal from database
         * @param {ProposalActionsRequestDto} proposalActionsRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async declineProposal(proposalActionsRequestDto: ProposalActionsRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseProposalActionsResponseDto>> {
            const localVarAxiosArgs = await ProposalControllerApiAxiosParamCreator(configuration).declineProposal(proposalActionsRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get Proposal by bucket process id from database
         * @param {RequestByBucketProcessIdDto} requestByBucketProcessIdDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetailProposal(requestByBucketProcessIdDto: RequestByBucketProcessIdDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoProposalResponseDto>> {
            const localVarAxiosArgs = await ProposalControllerApiAxiosParamCreator(configuration).getDetailProposal(requestByBucketProcessIdDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to Save Proposal to database
         * @param {number} [id] 
         * @param {string} [bucketProcessId] 
         * @param {any} [description] 
         * @param {string} [title] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveProposal(id?: number, bucketProcessId?: string, description?: any, title?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoProposalResponseDto>> {
            const localVarAxiosArgs = await ProposalControllerApiAxiosParamCreator(configuration).saveProposal(id, bucketProcessId, description, title, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to submit proposal from database
         * @param {ProposalSubmitRequestDto} proposalSubmitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitPipeline(proposalSubmitRequestDto: ProposalSubmitRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseProposalActionsResponseDto>> {
            const localVarAxiosArgs = await ProposalControllerApiAxiosParamCreator(configuration).submitPipeline(proposalSubmitRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProposalControllerApi - factory interface
 * @export
 */
export const ProposalControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to decline proposal from database
         * @param {ProposalActionsRequestDto} proposalActionsRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        declineProposal(proposalActionsRequestDto: ProposalActionsRequestDto, options?: any): AxiosPromise<BaseResponseProposalActionsResponseDto> {
            return ProposalControllerApiFp(configuration).declineProposal(proposalActionsRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get Proposal by bucket process id from database
         * @param {RequestByBucketProcessIdDto} requestByBucketProcessIdDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetailProposal(requestByBucketProcessIdDto: RequestByBucketProcessIdDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoProposalResponseDto> {
            return ProposalControllerApiFp(configuration).getDetailProposal(requestByBucketProcessIdDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to Save Proposal to database
         * @param {number} [id] 
         * @param {string} [bucketProcessId] 
         * @param {any} [description] 
         * @param {string} [title] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProposal(id?: number, bucketProcessId?: string, description?: any, title?: string, options?: any): AxiosPromise<BaseResponseGenericSingleDtoProposalResponseDto> {
            return ProposalControllerApiFp(configuration).saveProposal(id, bucketProcessId, description, title, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to submit proposal from database
         * @param {ProposalSubmitRequestDto} proposalSubmitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitPipeline(proposalSubmitRequestDto: ProposalSubmitRequestDto, options?: any): AxiosPromise<BaseResponseProposalActionsResponseDto> {
            return ProposalControllerApiFp(configuration).submitPipeline(proposalSubmitRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProposalControllerApi - object-oriented interface
 * @export
 * @class ProposalControllerApi
 * @extends {BaseAPI}
 */
export class ProposalControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to decline proposal from database
     * @param {ProposalActionsRequestDto} proposalActionsRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalControllerApi
     */
    public declineProposal(proposalActionsRequestDto: ProposalActionsRequestDto, options?: any) {
        return ProposalControllerApiFp(this.configuration).declineProposal(proposalActionsRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get Proposal by bucket process id from database
     * @param {RequestByBucketProcessIdDto} requestByBucketProcessIdDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalControllerApi
     */
    public getDetailProposal(requestByBucketProcessIdDto: RequestByBucketProcessIdDto, options?: any) {
        return ProposalControllerApiFp(this.configuration).getDetailProposal(requestByBucketProcessIdDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to Save Proposal to database
     * @param {number} [id] 
     * @param {string} [bucketProcessId] 
     * @param {any} [description] 
     * @param {string} [title] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalControllerApi
     */
    public saveProposal(id?: number, bucketProcessId?: string, description?: any, title?: string, options?: any) {
        return ProposalControllerApiFp(this.configuration).saveProposal(id, bucketProcessId, description, title, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to submit proposal from database
     * @param {ProposalSubmitRequestDto} proposalSubmitRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProposalControllerApi
     */
    public submitPipeline(proposalSubmitRequestDto: ProposalSubmitRequestDto, options?: any) {
        return ProposalControllerApiFp(this.configuration).submitPipeline(proposalSubmitRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


