// tslint:disable
/**
 * the title
 * My API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AskForInfoResponseDto
 */
export interface AskForInfoResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AskForInfoResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AskForInfoResponseDto
     */
    bucketProcess?: string;
    /**
     * 
     * @type {string}
     * @memberof AskForInfoResponseDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof AskForInfoResponseDto
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof AskForInfoResponseDto
     */
    modifiedDate?: string;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoAskForInfoResponseDto
 */
export interface BaseResponseGenericSingleDtoAskForInfoResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoAskForInfoResponseDto}
     * @memberof BaseResponseGenericSingleDtoAskForInfoResponseDto
     */
    data?: GenericSingleDtoAskForInfoResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoDelstRequestResponseDto
 */
export interface BaseResponseGenericSingleDtoDelstRequestResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoDelstRequestResponseDto}
     * @memberof BaseResponseGenericSingleDtoDelstRequestResponseDto
     */
    data?: GenericSingleDtoDelstRequestResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoRequestResponseDto
 */
export interface BaseResponseGenericSingleDtoRequestResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoRequestResponseDto}
     * @memberof BaseResponseGenericSingleDtoRequestResponseDto
     */
    data?: GenericSingleDtoRequestResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseString
 */
export interface BaseResponseString {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    data?: string;
}
/**
 * 
 * @export
 * @interface BucketProcessDTO
 */
export interface BucketProcessDTO {
    /**
     * 
     * @type {string}
     * @memberof BucketProcessDTO
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketProcessDTO
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketProcessDTO
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketProcessDTO
     */
    status?: string;
}
/**
 * 
 * @export
 * @interface DelstRequestResponseDto
 */
export interface DelstRequestResponseDto {
    /**
     * 
     * @type {number}
     * @memberof DelstRequestResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DelstRequestResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof DelstRequestResponseDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof DelstRequestResponseDto
     */
    additionalInformation?: string;
    /**
     * 
     * @type {string}
     * @memberof DelstRequestResponseDto
     */
    submissionType?: string;
    /**
     * 
     * @type {string}
     * @memberof DelstRequestResponseDto
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof DelstRequestResponseDto
     */
    modifiedDate?: string;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoAskForInfoResponseDto
 */
export interface GenericSingleDtoAskForInfoResponseDto {
    /**
     * 
     * @type {AskForInfoResponseDto}
     * @memberof GenericSingleDtoAskForInfoResponseDto
     */
    content?: AskForInfoResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoDelstRequestResponseDto
 */
export interface GenericSingleDtoDelstRequestResponseDto {
    /**
     * 
     * @type {DelstRequestResponseDto}
     * @memberof GenericSingleDtoDelstRequestResponseDto
     */
    content?: DelstRequestResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoRequestResponseDto
 */
export interface GenericSingleDtoRequestResponseDto {
    /**
     * 
     * @type {RequestResponseDto}
     * @memberof GenericSingleDtoRequestResponseDto
     */
    content?: RequestResponseDto;
}
/**
 * 
 * @export
 * @interface GetAskForInfoDto
 */
export interface GetAskForInfoDto {
    /**
     * 
     * @type {string}
     * @memberof GetAskForInfoDto
     */
    bucketProcess?: string;
}
/**
 * 
 * @export
 * @interface GetDelstRequestDto
 */
export interface GetDelstRequestDto {
    /**
     * 
     * @type {string}
     * @memberof GetDelstRequestDto
     */
    bucketProcessId?: string;
}
/**
 * 
 * @export
 * @interface GetRequestByProcessDto
 */
export interface GetRequestByProcessDto {
    /**
     * 
     * @type {string}
     * @memberof GetRequestByProcessDto
     */
    bucketProcess?: string;
}
/**
 * 
 * @export
 * @interface RequestResponseDto
 */
export interface RequestResponseDto {
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    modifiedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    bucketProcess?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestResponseDto
     */
    additionalInformation?: string;
}
/**
 * 
 * @export
 * @interface SaveAskForInfoRequestDto
 */
export interface SaveAskForInfoRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SaveAskForInfoRequestDto
     */
    bucketProcess?: string;
    /**
     * 
     * @type {any}
     * @memberof SaveAskForInfoRequestDto
     */
    notes?: any;
    /**
     * 
     * @type {string}
     * @memberof SaveAskForInfoRequestDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveAskForInfoRequestDto
     */
    module?: string;
}
/**
 * 
 * @export
 * @interface SaveDelstRequestDto
 */
export interface SaveDelstRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SaveDelstRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveDelstRequestDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveDelstRequestDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveDelstRequestDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveDelstRequestDto
     */
    submissionType?: string;
    /**
     * 
     * @type {any}
     * @memberof SaveDelstRequestDto
     */
    additionalInformation?: any;
}
/**
 * 
 * @export
 * @interface SaveTechnicalReviewRequestDto
 */
export interface SaveTechnicalReviewRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SaveTechnicalReviewRequestDto
     */
    bucketProcess?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveTechnicalReviewRequestDto
     */
    type?: SaveTechnicalReviewRequestDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SaveTechnicalReviewRequestDto
     */
    notes?: string;
    /**
     * 
     * @type {any}
     * @memberof SaveTechnicalReviewRequestDto
     */
    additionalInformation?: any;
    /**
     * 
     * @type {string}
     * @memberof SaveTechnicalReviewRequestDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveTechnicalReviewRequestDto
     */
    module?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SaveTechnicalReviewRequestDtoTypeEnum {
    PERMOHONAN = 'PERMOHONAN',
    SEGERA = 'SEGERA',
    BIASA = 'BIASA'
}


/**
 * AskForInfoControllerApi - axios parameter creator
 * @export
 */
export const AskForInfoControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to save ask for info to database
         * @param {string} [bucketProcess] 
         * @param {any} [notes] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creationAskForInfo: async (bucketProcess?: string, notes?: any, process?: string, module?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ask-for-info/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();


            if (bucketProcess !== undefined) { 
                localVarFormParams.append('bucketProcess', bucketProcess as any);
            }
    
            if (notes !== undefined) { 
                localVarFormParams.append('notes', notes as any);
            }
    
            if (process !== undefined) { 
                localVarFormParams.append('process', process as any);
            }
    
            if (module !== undefined) { 
                localVarFormParams.append('module', module as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get ask for info detail from database
         * @param {GetAskForInfoDto} getAskForInfoDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAskForInfo: async (getAskForInfoDto: GetAskForInfoDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getAskForInfoDto' is not null or undefined
            if (getAskForInfoDto === null || getAskForInfoDto === undefined) {
                throw new RequiredError('getAskForInfoDto','Required parameter getAskForInfoDto was null or undefined when calling getAskForInfo.');
            }
            const localVarPath = `/v1/ask-for-info/detail`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getAskForInfoDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getAskForInfoDto !== undefined ? getAskForInfoDto : {}) : (getAskForInfoDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AskForInfoControllerApi - functional programming interface
 * @export
 */
export const AskForInfoControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to save ask for info to database
         * @param {string} [bucketProcess] 
         * @param {any} [notes] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async creationAskForInfo(bucketProcess?: string, notes?: any, process?: string, module?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto>> {
            const localVarAxiosArgs = await AskForInfoControllerApiAxiosParamCreator(configuration).creationAskForInfo(bucketProcess, notes, process, module, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get ask for info detail from database
         * @param {GetAskForInfoDto} getAskForInfoDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAskForInfo(getAskForInfoDto: GetAskForInfoDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto>> {
            const localVarAxiosArgs = await AskForInfoControllerApiAxiosParamCreator(configuration).getAskForInfo(getAskForInfoDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AskForInfoControllerApi - factory interface
 * @export
 */
export const AskForInfoControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to save ask for info to database
         * @param {string} [bucketProcess] 
         * @param {any} [notes] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creationAskForInfo(bucketProcess?: string, notes?: any, process?: string, module?: string, options?: any): AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto> {
            return AskForInfoControllerApiFp(configuration).creationAskForInfo(bucketProcess, notes, process, module, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get ask for info detail from database
         * @param {GetAskForInfoDto} getAskForInfoDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAskForInfo(getAskForInfoDto: GetAskForInfoDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto> {
            return AskForInfoControllerApiFp(configuration).getAskForInfo(getAskForInfoDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AskForInfoControllerApi - object-oriented interface
 * @export
 * @class AskForInfoControllerApi
 * @extends {BaseAPI}
 */
export class AskForInfoControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to save ask for info to database
     * @param {string} [bucketProcess] 
     * @param {any} [notes] 
     * @param {string} [process] 
     * @param {string} [module] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AskForInfoControllerApi
     */
    public creationAskForInfo(bucketProcess?: string, notes?: any, process?: string, module?: string, options?: any) {
        return AskForInfoControllerApiFp(this.configuration).creationAskForInfo(bucketProcess, notes, process, module, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get ask for info detail from database
     * @param {GetAskForInfoDto} getAskForInfoDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AskForInfoControllerApi
     */
    public getAskForInfo(getAskForInfoDto: GetAskForInfoDto, options?: any) {
        return AskForInfoControllerApiFp(this.configuration).getAskForInfo(getAskForInfoDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * ByPassControllerApi - axios parameter creator
 * @export
 */
export const ByPassControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {BucketProcessDTO} bucketProcessDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        division: async (bucketProcessDTO: BucketProcessDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'bucketProcessDTO' is not null or undefined
            if (bucketProcessDTO === null || bucketProcessDTO === undefined) {
                throw new RequiredError('bucketProcessDTO','Required parameter bucketProcessDTO was null or undefined when calling division.');
            }
            const localVarPath = `/v1/bypass/division`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof bucketProcessDTO !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(bucketProcessDTO !== undefined ? bucketProcessDTO : {}) : (bucketProcessDTO || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {BucketProcessDTO} bucketProcessDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeDupe: async (bucketProcessDTO: BucketProcessDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'bucketProcessDTO' is not null or undefined
            if (bucketProcessDTO === null || bucketProcessDTO === undefined) {
                throw new RequiredError('bucketProcessDTO','Required parameter bucketProcessDTO was null or undefined when calling removeDupe.');
            }
            const localVarPath = `/v1/bypass/remove-duplicate-process`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof bucketProcessDTO !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(bucketProcessDTO !== undefined ? bucketProcessDTO : {}) : (bucketProcessDTO || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ByPassControllerApi - functional programming interface
 * @export
 */
export const ByPassControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {BucketProcessDTO} bucketProcessDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async division(bucketProcessDTO: BucketProcessDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto>> {
            const localVarAxiosArgs = await ByPassControllerApiAxiosParamCreator(configuration).division(bucketProcessDTO, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {BucketProcessDTO} bucketProcessDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeDupe(bucketProcessDTO: BucketProcessDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto>> {
            const localVarAxiosArgs = await ByPassControllerApiAxiosParamCreator(configuration).removeDupe(bucketProcessDTO, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ByPassControllerApi - factory interface
 * @export
 */
export const ByPassControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {BucketProcessDTO} bucketProcessDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        division(bucketProcessDTO: BucketProcessDTO, options?: any): AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto> {
            return ByPassControllerApiFp(configuration).division(bucketProcessDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BucketProcessDTO} bucketProcessDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeDupe(bucketProcessDTO: BucketProcessDTO, options?: any): AxiosPromise<BaseResponseGenericSingleDtoAskForInfoResponseDto> {
            return ByPassControllerApiFp(configuration).removeDupe(bucketProcessDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ByPassControllerApi - object-oriented interface
 * @export
 * @class ByPassControllerApi
 * @extends {BaseAPI}
 */
export class ByPassControllerApi extends BaseAPI {
    /**
     * 
     * @param {BucketProcessDTO} bucketProcessDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ByPassControllerApi
     */
    public division(bucketProcessDTO: BucketProcessDTO, options?: any) {
        return ByPassControllerApiFp(this.configuration).division(bucketProcessDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BucketProcessDTO} bucketProcessDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ByPassControllerApi
     */
    public removeDupe(bucketProcessDTO: BucketProcessDTO, options?: any) {
        return ByPassControllerApiFp(this.configuration).removeDupe(bucketProcessDTO, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * DelstRequestControllerApi - axios parameter creator
 * @export
 */
export const DelstRequestControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to save DELST Request to database
         * @param {string} [bucketProcessId] 
         * @param {string} [notes] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {string} [submissionType] 
         * @param {any} [additionalInformation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creationDelstRequest: async (bucketProcessId?: string, notes?: string, process?: string, module?: string, submissionType?: string, additionalInformation?: any, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/delst-request/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();


            if (bucketProcessId !== undefined) { 
                localVarFormParams.append('bucketProcessId', bucketProcessId as any);
            }
    
            if (notes !== undefined) { 
                localVarFormParams.append('notes', notes as any);
            }
    
            if (process !== undefined) { 
                localVarFormParams.append('process', process as any);
            }
    
            if (module !== undefined) { 
                localVarFormParams.append('module', module as any);
            }
    
            if (submissionType !== undefined) { 
                localVarFormParams.append('submissionType', submissionType as any);
            }
    
            if (additionalInformation !== undefined) { 
                localVarFormParams.append('additionalInformation', additionalInformation as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get DELST Request detail from database
         * @param {GetDelstRequestDto} getDelstRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDelstRequest: async (getDelstRequestDto: GetDelstRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getDelstRequestDto' is not null or undefined
            if (getDelstRequestDto === null || getDelstRequestDto === undefined) {
                throw new RequiredError('getDelstRequestDto','Required parameter getDelstRequestDto was null or undefined when calling getDelstRequest.');
            }
            const localVarPath = `/v1/delst-request/detail`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getDelstRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getDelstRequestDto !== undefined ? getDelstRequestDto : {}) : (getDelstRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DelstRequestControllerApi - functional programming interface
 * @export
 */
export const DelstRequestControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to save DELST Request to database
         * @param {string} [bucketProcessId] 
         * @param {string} [notes] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {string} [submissionType] 
         * @param {any} [additionalInformation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async creationDelstRequest(bucketProcessId?: string, notes?: string, process?: string, module?: string, submissionType?: string, additionalInformation?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoDelstRequestResponseDto>> {
            const localVarAxiosArgs = await DelstRequestControllerApiAxiosParamCreator(configuration).creationDelstRequest(bucketProcessId, notes, process, module, submissionType, additionalInformation, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get DELST Request detail from database
         * @param {GetDelstRequestDto} getDelstRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDelstRequest(getDelstRequestDto: GetDelstRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoDelstRequestResponseDto>> {
            const localVarAxiosArgs = await DelstRequestControllerApiAxiosParamCreator(configuration).getDelstRequest(getDelstRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DelstRequestControllerApi - factory interface
 * @export
 */
export const DelstRequestControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to save DELST Request to database
         * @param {string} [bucketProcessId] 
         * @param {string} [notes] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {string} [submissionType] 
         * @param {any} [additionalInformation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creationDelstRequest(bucketProcessId?: string, notes?: string, process?: string, module?: string, submissionType?: string, additionalInformation?: any, options?: any): AxiosPromise<BaseResponseGenericSingleDtoDelstRequestResponseDto> {
            return DelstRequestControllerApiFp(configuration).creationDelstRequest(bucketProcessId, notes, process, module, submissionType, additionalInformation, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get DELST Request detail from database
         * @param {GetDelstRequestDto} getDelstRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDelstRequest(getDelstRequestDto: GetDelstRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoDelstRequestResponseDto> {
            return DelstRequestControllerApiFp(configuration).getDelstRequest(getDelstRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DelstRequestControllerApi - object-oriented interface
 * @export
 * @class DelstRequestControllerApi
 * @extends {BaseAPI}
 */
export class DelstRequestControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to save DELST Request to database
     * @param {string} [bucketProcessId] 
     * @param {string} [notes] 
     * @param {string} [process] 
     * @param {string} [module] 
     * @param {string} [submissionType] 
     * @param {any} [additionalInformation] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DelstRequestControllerApi
     */
    public creationDelstRequest(bucketProcessId?: string, notes?: string, process?: string, module?: string, submissionType?: string, additionalInformation?: any, options?: any) {
        return DelstRequestControllerApiFp(this.configuration).creationDelstRequest(bucketProcessId, notes, process, module, submissionType, additionalInformation, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get DELST Request detail from database
     * @param {GetDelstRequestDto} getDelstRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DelstRequestControllerApi
     */
    public getDelstRequest(getDelstRequestDto: GetDelstRequestDto, options?: any) {
        return DelstRequestControllerApiFp(this.configuration).getDelstRequest(getDelstRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * HomeControllerApi - axios parameter creator
 * @export
 */
export const HomeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeControllerApi - functional programming interface
 * @export
 */
export const HomeControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async index(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await HomeControllerApiAxiosParamCreator(configuration).index(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HomeControllerApi - factory interface
 * @export
 */
export const HomeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index(options?: any): AxiosPromise<BaseResponseString> {
            return HomeControllerApiFp(configuration).index(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeControllerApi - object-oriented interface
 * @export
 * @class HomeControllerApi
 * @extends {BaseAPI}
 */
export class HomeControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeControllerApi
     */
    public index(options?: any) {
        return HomeControllerApiFp(this.configuration).index(options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * RequestControllerApi - axios parameter creator
 * @export
 */
export const RequestControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to save credit checking to database
         * @param {string} [bucketProcess] 
         * @param {string} [type] 
         * @param {string} [notes] 
         * @param {any} [additionalInformation] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creationRequestTechnicalReview: async (bucketProcess?: string, type?: string, notes?: string, additionalInformation?: any, process?: string, module?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/request/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();


            if (bucketProcess !== undefined) { 
                localVarFormParams.append('bucketProcess', bucketProcess as any);
            }
    
            if (type !== undefined) { 
                localVarFormParams.append('type', type as any);
            }
    
            if (notes !== undefined) { 
                localVarFormParams.append('notes', notes as any);
            }
    
            if (additionalInformation !== undefined) { 
                localVarFormParams.append('additionalInformation', additionalInformation as any);
            }
    
            if (process !== undefined) { 
                localVarFormParams.append('process', process as any);
            }
    
            if (module !== undefined) { 
                localVarFormParams.append('module', module as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get credit checking by process id
         * @param {GetRequestByProcessDto} getRequestByProcessDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestTechnicalReview: async (getRequestByProcessDto: GetRequestByProcessDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'getRequestByProcessDto' is not null or undefined
            if (getRequestByProcessDto === null || getRequestByProcessDto === undefined) {
                throw new RequiredError('getRequestByProcessDto','Required parameter getRequestByProcessDto was null or undefined when calling getRequestTechnicalReview.');
            }
            const localVarPath = `/v1/request/detail`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof getRequestByProcessDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(getRequestByProcessDto !== undefined ? getRequestByProcessDto : {}) : (getRequestByProcessDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RequestControllerApi - functional programming interface
 * @export
 */
export const RequestControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to save credit checking to database
         * @param {string} [bucketProcess] 
         * @param {string} [type] 
         * @param {string} [notes] 
         * @param {any} [additionalInformation] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async creationRequestTechnicalReview(bucketProcess?: string, type?: string, notes?: string, additionalInformation?: any, process?: string, module?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoRequestResponseDto>> {
            const localVarAxiosArgs = await RequestControllerApiAxiosParamCreator(configuration).creationRequestTechnicalReview(bucketProcess, type, notes, additionalInformation, process, module, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get credit checking by process id
         * @param {GetRequestByProcessDto} getRequestByProcessDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequestTechnicalReview(getRequestByProcessDto: GetRequestByProcessDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoRequestResponseDto>> {
            const localVarAxiosArgs = await RequestControllerApiAxiosParamCreator(configuration).getRequestTechnicalReview(getRequestByProcessDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RequestControllerApi - factory interface
 * @export
 */
export const RequestControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to save credit checking to database
         * @param {string} [bucketProcess] 
         * @param {string} [type] 
         * @param {string} [notes] 
         * @param {any} [additionalInformation] 
         * @param {string} [process] 
         * @param {string} [module] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creationRequestTechnicalReview(bucketProcess?: string, type?: string, notes?: string, additionalInformation?: any, process?: string, module?: string, options?: any): AxiosPromise<BaseResponseGenericSingleDtoRequestResponseDto> {
            return RequestControllerApiFp(configuration).creationRequestTechnicalReview(bucketProcess, type, notes, additionalInformation, process, module, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get credit checking by process id
         * @param {GetRequestByProcessDto} getRequestByProcessDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestTechnicalReview(getRequestByProcessDto: GetRequestByProcessDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoRequestResponseDto> {
            return RequestControllerApiFp(configuration).getRequestTechnicalReview(getRequestByProcessDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RequestControllerApi - object-oriented interface
 * @export
 * @class RequestControllerApi
 * @extends {BaseAPI}
 */
export class RequestControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to save credit checking to database
     * @param {string} [bucketProcess] 
     * @param {string} [type] 
     * @param {string} [notes] 
     * @param {any} [additionalInformation] 
     * @param {string} [process] 
     * @param {string} [module] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestControllerApi
     */
    public creationRequestTechnicalReview(bucketProcess?: string, type?: string, notes?: string, additionalInformation?: any, process?: string, module?: string, options?: any) {
        return RequestControllerApiFp(this.configuration).creationRequestTechnicalReview(bucketProcess, type, notes, additionalInformation, process, module, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get credit checking by process id
     * @param {GetRequestByProcessDto} getRequestByProcessDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestControllerApi
     */
    public getRequestTechnicalReview(getRequestByProcessDto: GetRequestByProcessDto, options?: any) {
        return RequestControllerApiFp(this.configuration).getRequestTechnicalReview(getRequestByProcessDto, options).then((request) => request(this.axios, this.basePath));
    }

}


