export const MODAL_FINANCING = {
  FORM_FACILITY: 'FORM_FACILITY',
  MODAL_DOCUMENT_PROVISION: 'MODAL_DOCUMENT_PROVISION',
  NEW_PROCESSING_TYPE: 'NEW_PROCESSING_TYPE',
  TABLE_PAYMENT_FACILITY_EXISTING: 'TABLE_PAYMENT_FACILITY_EXISTING',
};
