export const steps = [
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'debtor-information',
    'label': 'Informasi Customer',
    'urlPath': 'debtor-information',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'facility-overview',
    'label': 'Ringkasan Facilitas',
    'urlPath': 'facility-overview',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'executive-summary',
    'label': 'Executive Summary',
    'urlPath': 'executive-summary',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'esdd-report',
    'label': 'Environtmental and Social Due Diligence Report',
    'urlPath': 'esdd-report',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'corrective-action-plan',
    'label': 'Corrective Action Plan',
    'urlPath': 'corrective-action-plan',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'reporting-list-routine',
    'label': 'Daftar Pelaporan Rutin',
    'urlPath': 'reporting-list-routine',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'summary',
    'label': 'Kesimpulan',
    'urlPath': 'summary',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'draft-memo',
    'label': 'Draft Memo',
    'urlPath': 'draft-memo',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'view-all-document',
    'label': 'View All Document',
    'urlPath': 'view-all-document',
  },
  {
    'bucketProcessId': 'CC-00168',
    'enable': true,
    'isDone': false,
    'key': 'validation',
    'label': 'Validasi',
    'urlPath': 'validation',
  }
];
