export const ANNUAL_REVIEW_RATING_STANDALONE = 'ANNUAL_REVIEW_RATING_STANDALONE';
export const WAITING_APPROVAL_TL_STANDALONE = 'WAITING_APPROVAL_TL_STANDALONE';
export const RETURN_TO_STAFF_STANDALONE = 'RETURN_TO_STAFF_STANDALONE';
export const WAITING_APPROVAL_KADIV_STANDALONE = 'WAITING_APPROVAL_KADIV_STANDALONE';
export const RETURN_TO_TL_STANDALONE = 'RETURN_TO_TL_STANDALONE';

export const standaloneStatuses = [
  ANNUAL_REVIEW_RATING_STANDALONE,
  WAITING_APPROVAL_TL_STANDALONE,
  RETURN_TO_STAFF_STANDALONE,
  WAITING_APPROVAL_KADIV_STANDALONE,
  RETURN_TO_TL_STANDALONE,
];
