export const MOCK_STEPPER = [
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': true,
    'key': 'Customer-information',
    'label': 'Informasi Customer',
    'urlPath': 'Customer-information',
  },
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': false,
    'key': 'application',
    'label': 'Permohonan',
    'urlPath': 'application',
  },
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': false,
    'key': 'facility-overview',
    'label': 'Ringkasan Fasilitas',
    'urlPath': 'facility-overview',
  },
  {
    'action': {
      'SUBMIT': 'SUBMIT',
    },
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': false,
    'key': 'pk-processing-type-monitoring',
    'label': 'PK Processing Type Monitoring',
    'urlPath': 'pk-processing-type-monitoring',
  },
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': false,
    'key': 'additional-information',
    'label': 'Aditional Information',
    'urlPath': 'additional-information',
  },
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': false,
    'key': 'draft-memo',
    'label': 'Draft Memo',
    'urlPath': 'draft-memo',
  },
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': true,
    'key': 'view-all-document',
    'label': 'View All Document',
    'urlPath': 'view-all-document',
  },
  {
    'action': null,
    'bucketProcessId': 'SPFP-00069',
    'enable': true,
    'isDone': true,
    'key': 'validation',
    'label': 'Validasi',
    'urlPath': 'validation',
  }
];

export const MOCK_PROCESSID = 'SPFP-00069';
