// tslint:disable
/**
 * OpenAPI Dashboard Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface BaseResponseGenericBucketResponseDtoInquiryResponseDto
 */
export interface BaseResponseGenericBucketResponseDtoInquiryResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericBucketResponseDtoInquiryResponseDto}
     * @memberof BaseResponseGenericBucketResponseDtoInquiryResponseDto
     */
    data?: GenericBucketResponseDtoInquiryResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericBucketResponseDtoToDoResponseDto
 */
export interface BaseResponseGenericBucketResponseDtoToDoResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericBucketResponseDtoToDoResponseDto}
     * @memberof BaseResponseGenericBucketResponseDtoToDoResponseDto
     */
    data?: GenericBucketResponseDtoToDoResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericListDtoProcessResponseDto
 */
export interface BaseResponseGenericListDtoProcessResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericListDtoProcessResponseDto}
     * @memberof BaseResponseGenericListDtoProcessResponseDto
     */
    data?: GenericListDtoProcessResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericListDtoStatusResponseDto
 */
export interface BaseResponseGenericListDtoStatusResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericListDtoStatusResponseDto}
     * @memberof BaseResponseGenericListDtoStatusResponseDto
     */
    data?: GenericListDtoStatusResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseString
 */
export interface BaseResponseString {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    data?: string;
}
/**
 * 
 * @export
 * @interface GenericBucketRequestDtoMapStringObject
 */
export interface GenericBucketRequestDtoMapStringObject {
    /**
     * 
     * @type {PageRequestDto}
     * @memberof GenericBucketRequestDtoMapStringObject
     */
    page?: PageRequestDto;
    /**
     * 
     * @type {SortRequestDto}
     * @memberof GenericBucketRequestDtoMapStringObject
     */
    sortList?: SortRequestDto;
    /**
     * 
     * @type {SearchDetailRequestDto}
     * @memberof GenericBucketRequestDtoMapStringObject
     */
    searchDetail?: SearchDetailRequestDto;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof GenericBucketRequestDtoMapStringObject
     */
    filter?: { [key: string]: object; };
}
/**
 * 
 * @export
 * @interface GenericBucketRequestDtoToDoRequestDto
 */
export interface GenericBucketRequestDtoToDoRequestDto {
    /**
     * 
     * @type {PageRequestDto}
     * @memberof GenericBucketRequestDtoToDoRequestDto
     */
    page?: PageRequestDto;
    /**
     * 
     * @type {SortRequestDto}
     * @memberof GenericBucketRequestDtoToDoRequestDto
     */
    sortList?: SortRequestDto;
    /**
     * 
     * @type {SearchDetailRequestDto}
     * @memberof GenericBucketRequestDtoToDoRequestDto
     */
    searchDetail?: SearchDetailRequestDto;
    /**
     * 
     * @type {ToDoRequestDto}
     * @memberof GenericBucketRequestDtoToDoRequestDto
     */
    filter?: ToDoRequestDto;
}
/**
 * 
 * @export
 * @interface GenericBucketResponseDtoInquiryResponseDto
 */
export interface GenericBucketResponseDtoInquiryResponseDto {
    /**
     * 
     * @type {Array<InquiryResponseDto>}
     * @memberof GenericBucketResponseDtoInquiryResponseDto
     */
    contents?: Array<InquiryResponseDto>;
    /**
     * 
     * @type {PageResponseDto}
     * @memberof GenericBucketResponseDtoInquiryResponseDto
     */
    page?: PageResponseDto;
}
/**
 * 
 * @export
 * @interface GenericBucketResponseDtoToDoResponseDto
 */
export interface GenericBucketResponseDtoToDoResponseDto {
    /**
     * 
     * @type {Array<ToDoResponseDto>}
     * @memberof GenericBucketResponseDtoToDoResponseDto
     */
    contents?: Array<ToDoResponseDto>;
    /**
     * 
     * @type {PageResponseDto}
     * @memberof GenericBucketResponseDtoToDoResponseDto
     */
    page?: PageResponseDto;
}
/**
 * 
 * @export
 * @interface GenericListDtoProcessResponseDto
 */
export interface GenericListDtoProcessResponseDto {
    /**
     * 
     * @type {Array<ProcessResponseDto>}
     * @memberof GenericListDtoProcessResponseDto
     */
    contents?: Array<ProcessResponseDto>;
}
/**
 * 
 * @export
 * @interface GenericListDtoStatusResponseDto
 */
export interface GenericListDtoStatusResponseDto {
    /**
     * 
     * @type {Array<StatusResponseDto>}
     * @memberof GenericListDtoStatusResponseDto
     */
    contents?: Array<StatusResponseDto>;
}
/**
 * 
 * @export
 * @interface InquiryResponseDto
 */
export interface InquiryResponseDto {
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    bucketMasterId?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    processLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    commitment?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    debtorName?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    groupName?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    staffName?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    statusLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryResponseDto
     */
    url?: string;
}
/**
 * 
 * @export
 * @interface PageRequestDto
 */
export interface PageRequestDto {
    /**
     * 
     * @type {number}
     * @memberof PageRequestDto
     */
    noPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRequestDto
     */
    itemPerPage?: number;
}
/**
 * 
 * @export
 * @interface PageResponseDto
 */
export interface PageResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    noPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    itemPerPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    totalPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseDto
     */
    totalData?: number;
}
/**
 * 
 * @export
 * @interface ProcessResponseDto
 */
export interface ProcessResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ProcessResponseDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessResponseDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessResponseDto
     */
    label?: string;
}
/**
 * 
 * @export
 * @interface SearchDetailRequestDto
 */
export interface SearchDetailRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SearchDetailRequestDto
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchDetailRequestDto
     */
    value?: string;
}
/**
 * 
 * @export
 * @interface SortRequestDto
 */
export interface SortRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SortRequestDto
     */
    columnName?: string;
    /**
     * 
     * @type {string}
     * @memberof SortRequestDto
     */
    sortType?: string;
}
/**
 * 
 * @export
 * @interface StatusRequestDto
 */
export interface StatusRequestDto {
    /**
     * 
     * @type {string}
     * @memberof StatusRequestDto
     */
    module: string;
    /**
     * 
     * @type {string}
     * @memberof StatusRequestDto
     */
    process: string;
}
/**
 * 
 * @export
 * @interface StatusResponseDto
 */
export interface StatusResponseDto {
    /**
     * 
     * @type {string}
     * @memberof StatusResponseDto
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusResponseDto
     */
    statusLabel?: string;
}
/**
 * 
 * @export
 * @interface ToDoRequestDto
 */
export interface ToDoRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ToDoRequestDto
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoRequestDto
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoRequestDto
     */
    debtorName?: string;
}
/**
 * 
 * @export
 * @interface ToDoResponseDto
 */
export interface ToDoResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    debtorName?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    statusLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    modifiedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ToDoResponseDto
     */
    url?: string;
}

/**
 * HomeControllerApi - axios parameter creator
 * @export
 */
export const HomeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeControllerApi - functional programming interface
 * @export
 */
export const HomeControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async index(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await HomeControllerApiAxiosParamCreator(configuration).index(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HomeControllerApi - factory interface
 * @export
 */
export const HomeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index(options?: any): AxiosPromise<BaseResponseString> {
            return HomeControllerApiFp(configuration).index(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeControllerApi - object-oriented interface
 * @export
 * @class HomeControllerApi
 * @extends {BaseAPI}
 */
export class HomeControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeControllerApi
     */
    public index(options?: any) {
        return HomeControllerApiFp(this.configuration).index(options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * InquiryControllerApi - axios parameter creator
 * @export
 */
export const InquiryControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get All Process
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProcess: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/inquiry/all-process`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get Bucket Inquiry
         * @param {GenericBucketRequestDtoMapStringObject} genericBucketRequestDtoMapStringObject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucketInquiry: async (genericBucketRequestDtoMapStringObject: GenericBucketRequestDtoMapStringObject, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genericBucketRequestDtoMapStringObject' is not null or undefined
            if (genericBucketRequestDtoMapStringObject === null || genericBucketRequestDtoMapStringObject === undefined) {
                throw new RequiredError('genericBucketRequestDtoMapStringObject','Required parameter genericBucketRequestDtoMapStringObject was null or undefined when calling getBucketInquiry.');
            }
            const localVarPath = `/v1/inquiry/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof genericBucketRequestDtoMapStringObject !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(genericBucketRequestDtoMapStringObject !== undefined ? genericBucketRequestDtoMapStringObject : {}) : (genericBucketRequestDtoMapStringObject || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get Status
         * @param {StatusRequestDto} statusRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus: async (statusRequestDto: StatusRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'statusRequestDto' is not null or undefined
            if (statusRequestDto === null || statusRequestDto === undefined) {
                throw new RequiredError('statusRequestDto','Required parameter statusRequestDto was null or undefined when calling getStatus.');
            }
            const localVarPath = `/v1/inquiry/status`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof statusRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(statusRequestDto !== undefined ? statusRequestDto : {}) : (statusRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InquiryControllerApi - functional programming interface
 * @export
 */
export const InquiryControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get All Process
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllProcess(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericListDtoProcessResponseDto>> {
            const localVarAxiosArgs = await InquiryControllerApiAxiosParamCreator(configuration).getAllProcess(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get Bucket Inquiry
         * @param {GenericBucketRequestDtoMapStringObject} genericBucketRequestDtoMapStringObject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBucketInquiry(genericBucketRequestDtoMapStringObject: GenericBucketRequestDtoMapStringObject, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericBucketResponseDtoInquiryResponseDto>> {
            const localVarAxiosArgs = await InquiryControllerApiAxiosParamCreator(configuration).getBucketInquiry(genericBucketRequestDtoMapStringObject, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get Status
         * @param {StatusRequestDto} statusRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatus(statusRequestDto: StatusRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericListDtoStatusResponseDto>> {
            const localVarAxiosArgs = await InquiryControllerApiAxiosParamCreator(configuration).getStatus(statusRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InquiryControllerApi - factory interface
 * @export
 */
export const InquiryControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to get All Process
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProcess(options?: any): AxiosPromise<BaseResponseGenericListDtoProcessResponseDto> {
            return InquiryControllerApiFp(configuration).getAllProcess(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get Bucket Inquiry
         * @param {GenericBucketRequestDtoMapStringObject} genericBucketRequestDtoMapStringObject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucketInquiry(genericBucketRequestDtoMapStringObject: GenericBucketRequestDtoMapStringObject, options?: any): AxiosPromise<BaseResponseGenericBucketResponseDtoInquiryResponseDto> {
            return InquiryControllerApiFp(configuration).getBucketInquiry(genericBucketRequestDtoMapStringObject, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get Status
         * @param {StatusRequestDto} statusRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(statusRequestDto: StatusRequestDto, options?: any): AxiosPromise<BaseResponseGenericListDtoStatusResponseDto> {
            return InquiryControllerApiFp(configuration).getStatus(statusRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InquiryControllerApi - object-oriented interface
 * @export
 * @class InquiryControllerApi
 * @extends {BaseAPI}
 */
export class InquiryControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to get All Process
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InquiryControllerApi
     */
    public getAllProcess(options?: any) {
        return InquiryControllerApiFp(this.configuration).getAllProcess(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get Bucket Inquiry
     * @param {GenericBucketRequestDtoMapStringObject} genericBucketRequestDtoMapStringObject 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InquiryControllerApi
     */
    public getBucketInquiry(genericBucketRequestDtoMapStringObject: GenericBucketRequestDtoMapStringObject, options?: any) {
        return InquiryControllerApiFp(this.configuration).getBucketInquiry(genericBucketRequestDtoMapStringObject, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get Status
     * @param {StatusRequestDto} statusRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InquiryControllerApi
     */
    public getStatus(statusRequestDto: StatusRequestDto, options?: any) {
        return InquiryControllerApiFp(this.configuration).getStatus(statusRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * TodoControllerApi - axios parameter creator
 * @export
 */
export const TodoControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get Bucket Todo
         * @param {GenericBucketRequestDtoToDoRequestDto} genericBucketRequestDtoToDoRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucketTodo: async (genericBucketRequestDtoToDoRequestDto: GenericBucketRequestDtoToDoRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'genericBucketRequestDtoToDoRequestDto' is not null or undefined
            if (genericBucketRequestDtoToDoRequestDto === null || genericBucketRequestDtoToDoRequestDto === undefined) {
                throw new RequiredError('genericBucketRequestDtoToDoRequestDto','Required parameter genericBucketRequestDtoToDoRequestDto was null or undefined when calling getBucketTodo.');
            }
            const localVarPath = `/v1/todo/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof genericBucketRequestDtoToDoRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(genericBucketRequestDtoToDoRequestDto !== undefined ? genericBucketRequestDtoToDoRequestDto : {}) : (genericBucketRequestDtoToDoRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodoControllerApi - functional programming interface
 * @export
 */
export const TodoControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to get Bucket Todo
         * @param {GenericBucketRequestDtoToDoRequestDto} genericBucketRequestDtoToDoRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBucketTodo(genericBucketRequestDtoToDoRequestDto: GenericBucketRequestDtoToDoRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericBucketResponseDtoToDoResponseDto>> {
            const localVarAxiosArgs = await TodoControllerApiAxiosParamCreator(configuration).getBucketTodo(genericBucketRequestDtoToDoRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TodoControllerApi - factory interface
 * @export
 */
export const TodoControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to get Bucket Todo
         * @param {GenericBucketRequestDtoToDoRequestDto} genericBucketRequestDtoToDoRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucketTodo(genericBucketRequestDtoToDoRequestDto: GenericBucketRequestDtoToDoRequestDto, options?: any): AxiosPromise<BaseResponseGenericBucketResponseDtoToDoResponseDto> {
            return TodoControllerApiFp(configuration).getBucketTodo(genericBucketRequestDtoToDoRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TodoControllerApi - object-oriented interface
 * @export
 * @class TodoControllerApi
 * @extends {BaseAPI}
 */
export class TodoControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to get Bucket Todo
     * @param {GenericBucketRequestDtoToDoRequestDto} genericBucketRequestDtoToDoRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoControllerApi
     */
    public getBucketTodo(genericBucketRequestDtoToDoRequestDto: GenericBucketRequestDtoToDoRequestDto, options?: any) {
        return TodoControllerApiFp(this.configuration).getBucketTodo(genericBucketRequestDtoToDoRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


