export const action = {
  DECLINE: 'CANCEL',
  KADIV_TO_STAFF: 'MEMO_SUPPLEMENT_RETURN_FROM_KADIV_TO_STAFF',
  KADIV_TO_TL: 'MEMO_SUPPLEMENT_RETURN_FROM_KADIV_TO_TL',
  SUBMIT: 'SUBMIT',
  TL_TO_STAFF: 'MEMO_SUPPLEMENT_RETURN_FROM_TL_TO_STAFF',
};
