export const modal = {
  DECLINE: 'DECLINE',
  DIGITAL_MEMO_DRAFT_MODAL: 'DIGITAL_MEMO_DRAFT_MODAL',
  FINANCING_DOCUMENT_DRAFT_MODAL: 'FINANCING_DOCUMENT_DRAFT_MODAL',
  GENERATE_DRAFT_MEMO: 'GENERATE_DRAFT_MEMO',
  HISTORY_DRAFT_MEMO: 'HISTORY_DRAFT_MEMO',
  SUPPORTING_DOCUMENT_DRAFT_MODAL: 'SUPPORTING_DOCUMENT_DRAFT_MODAL',
};

export const SUBMIT = 'SUBMIT';
export const DECLINE = 'DECLINE';
