export const modal = {
  PAYMENT_FACILITY_DETAIL: 'PAYMENT_FACILITY_DETAIL',
  PAYMENT_FACILITY_FORM: 'PAYMENT_FACILITY_FORM',
  PAYMENT_FACILITY_NEW: 'PAYMENT_FACILITY_NEW',
  TABLE_PAYMENT_FACILITY_EXISTING: 'TABLEPAYMENT_FACILITY_EXISTING',
};
