export const modalData = {
  MODAL_DEBTOR_DETAIL_NEW: 'MODAL_DEBTOR_DETAIL_NEW',
  MODAL_MANAGEMENT_DETAIL_EXISTING: 'MODAL_MANAGEMENT_DETAIL_EXISTING',
  MODAL_MANAGEMENT_DETAIL_NEW: 'MODAL_MANAGEMENT_DETAIL_NEW',
  MODAL_MANAGEMENT_EXISTING: 'MODAL_MANAGEMENT_EXISTING',
  MODAL_MANAGEMENT_NEW: 'MODAL_MANAGEMENT_NEW',
  MODAL_SHAREHOLDER_DETAIL_EXISTING: 'MODAL_SHAREHOLDER_DETAIL_EXISTING',
  MODAL_SHAREHOLDER_DETAIL_NEW: 'MODAL_SHAREHOLDER_DETAIL_NEW',
  MODAL_SHAREHOLDER_EXISTING: 'MODAL_SHAREHOLDER_EXISTING',
  MODAL_SHAREHOLDER_NEW: 'MODAL_SHAREHOLDER_NEW',
  MODAL_TABLE_DEBTOR_NEW: 'MODAL_TABLE_DEBTOR_NEW',
};
