// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface BaseResponseGenericListDtoMipStepResponseDto
 */
export interface BaseResponseGenericListDtoMipStepResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericListDtoMipStepResponseDto}
     * @memberof BaseResponseGenericListDtoMipStepResponseDto
     */
    data?: GenericListDtoMipStepResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoMipStepProgressResponseDto
 */
export interface BaseResponseGenericSingleDtoMipStepProgressResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoMipStepProgressResponseDto}
     * @memberof BaseResponseGenericSingleDtoMipStepProgressResponseDto
     */
    data?: GenericSingleDtoMipStepProgressResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseGenericSingleDtoMipStepResponseDto
 */
export interface BaseResponseGenericSingleDtoMipStepResponseDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    timestamp?: string;
    /**
     * 
     * @type {GenericSingleDtoMipStepResponseDto}
     * @memberof BaseResponseGenericSingleDtoMipStepResponseDto
     */
    data?: GenericSingleDtoMipStepResponseDto;
}
/**
 * 
 * @export
 * @interface BaseResponseString
 */
export interface BaseResponseString {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorSource?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    errorDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    data?: string;
}
/**
 * 
 * @export
 * @interface DynamicStepRequestDto
 */
export interface DynamicStepRequestDto {
    /**
     * 
     * @type {number}
     * @memberof DynamicStepRequestDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    urlPath?: string;
    /**
     * 
     * @type {number}
     * @memberof DynamicStepRequestDto
     */
    sequence?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    roleAccess?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    statusAccess?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    statusShow?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicStepRequestDto
     */
    typeStep?: string;
}
/**
 * 
 * @export
 * @interface GenericListDtoMipStepResponseDto
 */
export interface GenericListDtoMipStepResponseDto {
    /**
     * 
     * @type {Array<MipStepResponseDto>}
     * @memberof GenericListDtoMipStepResponseDto
     */
    contents?: Array<MipStepResponseDto>;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoMipStepProgressResponseDto
 */
export interface GenericSingleDtoMipStepProgressResponseDto {
    /**
     * 
     * @type {MipStepProgressResponseDto}
     * @memberof GenericSingleDtoMipStepProgressResponseDto
     */
    content?: MipStepProgressResponseDto;
}
/**
 * 
 * @export
 * @interface GenericSingleDtoMipStepResponseDto
 */
export interface GenericSingleDtoMipStepResponseDto {
    /**
     * 
     * @type {MipStepResponseDto}
     * @memberof GenericSingleDtoMipStepResponseDto
     */
    content?: MipStepResponseDto;
}
/**
 * 
 * @export
 * @interface MappingDynamicStepRequestDto
 */
export interface MappingDynamicStepRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MappingDynamicStepRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof MappingDynamicStepRequestDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof MappingDynamicStepRequestDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof MappingDynamicStepRequestDto
     */
    typeStep?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MappingDynamicStepRequestDto
     */
    keys?: Array<string>;
}
/**
 * 
 * @export
 * @interface MipStepProgressResponseDto
 */
export interface MipStepProgressResponseDto {
    /**
     * 
     * @type {number}
     * @memberof MipStepProgressResponseDto
     */
    progress?: number;
    /**
     * 
     * @type {string}
     * @memberof MipStepProgressResponseDto
     */
    from?: string;
    /**
     * 
     * @type {Array<MipStepResponseDto>}
     * @memberof MipStepProgressResponseDto
     */
    steps?: Array<MipStepResponseDto>;
}
/**
 * 
 * @export
 * @interface MipStepResponseDto
 */
export interface MipStepResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MipStepResponseDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof MipStepResponseDto
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof MipStepResponseDto
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof MipStepResponseDto
     */
    urlPath?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MipStepResponseDto
     */
    enable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MipStepResponseDto
     */
    isDone?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MipStepResponseDto
     */
    action?: { [key: string]: string; };
}
/**
 * 
 * @export
 * @interface ProcessorPublishMessage
 */
export interface ProcessorPublishMessage {
    /**
     * 
     * @type {string}
     * @memberof ProcessorPublishMessage
     */
    topicName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorPublishMessage
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorPublishMessage
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorPublishMessage
     */
    eventName?: string;
    /**
     * 
     * @type {object}
     * @memberof ProcessorPublishMessage
     */
    data?: object;
}
/**
 * 
 * @export
 * @interface RequestByProcessIdDtoString
 */
export interface RequestByProcessIdDtoString {
    /**
     * 
     * @type {string}
     * @memberof RequestByProcessIdDtoString
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestByProcessIdDtoString
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestByProcessIdDtoString
     */
    process?: string;
}
/**
 * 
 * @export
 * @interface SubmitRequestDto
 */
export interface SubmitRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestDto
     */
    bucketProcessId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestDto
     */
    module?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestDto
     */
    process?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestDto
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestDto
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubmitRequestDto
     */
    isCompleteEditAskForInfo?: boolean;
}

/**
 * DynamicStepperControllerApi - axios parameter creator
 * @export
 */
export const DynamicStepperControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to add stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addStepper: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling addStepper.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/add`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to create mapping stepper
         * @param {MappingDynamicStepRequestDto} mappingDynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMappingStepper: async (mappingDynamicStepRequestDto: MappingDynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'mappingDynamicStepRequestDto' is not null or undefined
            if (mappingDynamicStepRequestDto === null || mappingDynamicStepRequestDto === undefined) {
                throw new RequiredError('mappingDynamicStepRequestDto','Required parameter mappingDynamicStepRequestDto was null or undefined when calling createMappingStepper.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/mapping-step`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof mappingDynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(mappingDynamicStepRequestDto !== undefined ? mappingDynamicStepRequestDto : {}) : (mappingDynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to delete mapping stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMappingStepper: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling deleteMappingStepper.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/delete-mapping-step`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to delete stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStepper: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling deleteStepper.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/delete`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get all dynamic stepper by module and process
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDynamicStepper: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling getAllDynamicStepper.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/get`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get stepper by bucket process id
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStepperBucketProcess: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling getStepperBucketProcess.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/bucket-process-step`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to get stepper by id
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStepperById: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling getStepperById.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/getById`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to update stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStepper: async (dynamicStepRequestDto: DynamicStepRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dynamicStepRequestDto' is not null or undefined
            if (dynamicStepRequestDto === null || dynamicStepRequestDto === undefined) {
                throw new RequiredError('dynamicStepRequestDto','Required parameter dynamicStepRequestDto was null or undefined when calling updateStepper.');
            }
            const localVarPath = `/v1/processor/dynamic-stepper/update`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof dynamicStepRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(dynamicStepRequestDto !== undefined ? dynamicStepRequestDto : {}) : (dynamicStepRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DynamicStepperControllerApi - functional programming interface
 * @export
 */
export const DynamicStepperControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to add stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).addStepper(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to create mapping stepper
         * @param {MappingDynamicStepRequestDto} mappingDynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMappingStepper(mappingDynamicStepRequestDto: MappingDynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericListDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).createMappingStepper(mappingDynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to delete mapping stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMappingStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).deleteMappingStepper(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to delete stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).deleteStepper(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get all dynamic stepper by module and process
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDynamicStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericListDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).getAllDynamicStepper(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get stepper by bucket process id
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStepperBucketProcess(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericListDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).getStepperBucketProcess(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to get stepper by id
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStepperById(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).getStepperById(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to update stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto>> {
            const localVarAxiosArgs = await DynamicStepperControllerApiAxiosParamCreator(configuration).updateStepper(dynamicStepRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DynamicStepperControllerApi - factory interface
 * @export
 */
export const DynamicStepperControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to add stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).addStepper(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to create mapping stepper
         * @param {MappingDynamicStepRequestDto} mappingDynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMappingStepper(mappingDynamicStepRequestDto: MappingDynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericListDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).createMappingStepper(mappingDynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to delete mapping stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMappingStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).deleteMappingStepper(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to delete stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).deleteStepper(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get all dynamic stepper by module and process
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDynamicStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericListDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).getAllDynamicStepper(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get stepper by bucket process id
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStepperBucketProcess(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericListDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).getStepperBucketProcess(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to get stepper by id
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStepperById(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).getStepperById(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to update stepper
         * @param {DynamicStepRequestDto} dynamicStepRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any): AxiosPromise<BaseResponseGenericSingleDtoMipStepResponseDto> {
            return DynamicStepperControllerApiFp(configuration).updateStepper(dynamicStepRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DynamicStepperControllerApi - object-oriented interface
 * @export
 * @class DynamicStepperControllerApi
 * @extends {BaseAPI}
 */
export class DynamicStepperControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to add stepper
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public addStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).addStepper(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to create mapping stepper
     * @param {MappingDynamicStepRequestDto} mappingDynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public createMappingStepper(mappingDynamicStepRequestDto: MappingDynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).createMappingStepper(mappingDynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to delete mapping stepper
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public deleteMappingStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).deleteMappingStepper(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to delete stepper
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public deleteStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).deleteStepper(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get all dynamic stepper by module and process
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public getAllDynamicStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).getAllDynamicStepper(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get stepper by bucket process id
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public getStepperBucketProcess(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).getStepperBucketProcess(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to get stepper by id
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public getStepperById(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).getStepperById(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to update stepper
     * @param {DynamicStepRequestDto} dynamicStepRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DynamicStepperControllerApi
     */
    public updateStepper(dynamicStepRequestDto: DynamicStepRequestDto, options?: any) {
        return DynamicStepperControllerApiFp(this.configuration).updateStepper(dynamicStepRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * HomeControllerApi - axios parameter creator
 * @export
 */
export const HomeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeControllerApi - functional programming interface
 * @export
 */
export const HomeControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async index(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await HomeControllerApiAxiosParamCreator(configuration).index(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HomeControllerApi - factory interface
 * @export
 */
export const HomeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        index(options?: any): AxiosPromise<BaseResponseString> {
            return HomeControllerApiFp(configuration).index(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeControllerApi - object-oriented interface
 * @export
 * @class HomeControllerApi
 * @extends {BaseAPI}
 */
export class HomeControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeControllerApi
     */
    public index(options?: any) {
        return HomeControllerApiFp(this.configuration).index(options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * ProcessorControllerApi - axios parameter creator
 * @export
 */
export const ProcessorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to publish message from http
         * @param {ProcessorPublishMessage} processorPublishMessage 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        httpPublishMessage: async (processorPublishMessage: ProcessorPublishMessage, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'processorPublishMessage' is not null or undefined
            if (processorPublishMessage === null || processorPublishMessage === undefined) {
                throw new RequiredError('processorPublishMessage','Required parameter processorPublishMessage was null or undefined when calling httpPublishMessage.');
            }
            const localVarPath = `/v1/processor/publish`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof processorPublishMessage !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(processorPublishMessage !== undefined ? processorPublishMessage : {}) : (processorPublishMessage || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to submit bucket
         * @param {RequestByProcessIdDtoString} requestByProcessIdDtoString 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stepperBucket: async (requestByProcessIdDtoString: RequestByProcessIdDtoString, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestByProcessIdDtoString' is not null or undefined
            if (requestByProcessIdDtoString === null || requestByProcessIdDtoString === undefined) {
                throw new RequiredError('requestByProcessIdDtoString','Required parameter requestByProcessIdDtoString was null or undefined when calling stepperBucket.');
            }
            const localVarPath = `/v1/processor/bucket/stepper`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof requestByProcessIdDtoString !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(requestByProcessIdDtoString !== undefined ? requestByProcessIdDtoString : {}) : (requestByProcessIdDtoString || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to submit bucket
         * @param {SubmitRequestDto} submitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitBucketProcess: async (submitRequestDto: SubmitRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'submitRequestDto' is not null or undefined
            if (submitRequestDto === null || submitRequestDto === undefined) {
                throw new RequiredError('submitRequestDto','Required parameter submitRequestDto was null or undefined when calling submitBucketProcess.');
            }
            const localVarPath = `/v1/processor/bucket/submit`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof submitRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(submitRequestDto !== undefined ? submitRequestDto : {}) : (submitRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary API to submit new workflow
         * @param {SubmitRequestDto} submitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitNewWorkflow: async (submitRequestDto: SubmitRequestDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'submitRequestDto' is not null or undefined
            if (submitRequestDto === null || submitRequestDto === undefined) {
                throw new RequiredError('submitRequestDto','Required parameter submitRequestDto was null or undefined when calling submitNewWorkflow.');
            }
            const localVarPath = `/v1/processor/bucket/workflow`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof submitRequestDto !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(submitRequestDto !== undefined ? submitRequestDto : {}) : (submitRequestDto || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProcessorControllerApi - functional programming interface
 * @export
 */
export const ProcessorControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API to publish message from http
         * @param {ProcessorPublishMessage} processorPublishMessage 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async httpPublishMessage(processorPublishMessage: ProcessorPublishMessage, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await ProcessorControllerApiAxiosParamCreator(configuration).httpPublishMessage(processorPublishMessage, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to submit bucket
         * @param {RequestByProcessIdDtoString} requestByProcessIdDtoString 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stepperBucket(requestByProcessIdDtoString: RequestByProcessIdDtoString, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGenericSingleDtoMipStepProgressResponseDto>> {
            const localVarAxiosArgs = await ProcessorControllerApiAxiosParamCreator(configuration).stepperBucket(requestByProcessIdDtoString, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to submit bucket
         * @param {SubmitRequestDto} submitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitBucketProcess(submitRequestDto: SubmitRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await ProcessorControllerApiAxiosParamCreator(configuration).submitBucketProcess(submitRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary API to submit new workflow
         * @param {SubmitRequestDto} submitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitNewWorkflow(submitRequestDto: SubmitRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await ProcessorControllerApiAxiosParamCreator(configuration).submitNewWorkflow(submitRequestDto, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProcessorControllerApi - factory interface
 * @export
 */
export const ProcessorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary API to publish message from http
         * @param {ProcessorPublishMessage} processorPublishMessage 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        httpPublishMessage(processorPublishMessage: ProcessorPublishMessage, options?: any): AxiosPromise<object> {
            return ProcessorControllerApiFp(configuration).httpPublishMessage(processorPublishMessage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to submit bucket
         * @param {RequestByProcessIdDtoString} requestByProcessIdDtoString 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stepperBucket(requestByProcessIdDtoString: RequestByProcessIdDtoString, options?: any): AxiosPromise<BaseResponseGenericSingleDtoMipStepProgressResponseDto> {
            return ProcessorControllerApiFp(configuration).stepperBucket(requestByProcessIdDtoString, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to submit bucket
         * @param {SubmitRequestDto} submitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitBucketProcess(submitRequestDto: SubmitRequestDto, options?: any): AxiosPromise<BaseResponseString> {
            return ProcessorControllerApiFp(configuration).submitBucketProcess(submitRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary API to submit new workflow
         * @param {SubmitRequestDto} submitRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitNewWorkflow(submitRequestDto: SubmitRequestDto, options?: any): AxiosPromise<BaseResponseString> {
            return ProcessorControllerApiFp(configuration).submitNewWorkflow(submitRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProcessorControllerApi - object-oriented interface
 * @export
 * @class ProcessorControllerApi
 * @extends {BaseAPI}
 */
export class ProcessorControllerApi extends BaseAPI {
    /**
     * 
     * @summary API to publish message from http
     * @param {ProcessorPublishMessage} processorPublishMessage 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessorControllerApi
     */
    public httpPublishMessage(processorPublishMessage: ProcessorPublishMessage, options?: any) {
        return ProcessorControllerApiFp(this.configuration).httpPublishMessage(processorPublishMessage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to submit bucket
     * @param {RequestByProcessIdDtoString} requestByProcessIdDtoString 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessorControllerApi
     */
    public stepperBucket(requestByProcessIdDtoString: RequestByProcessIdDtoString, options?: any) {
        return ProcessorControllerApiFp(this.configuration).stepperBucket(requestByProcessIdDtoString, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to submit bucket
     * @param {SubmitRequestDto} submitRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessorControllerApi
     */
    public submitBucketProcess(submitRequestDto: SubmitRequestDto, options?: any) {
        return ProcessorControllerApiFp(this.configuration).submitBucketProcess(submitRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary API to submit new workflow
     * @param {SubmitRequestDto} submitRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessorControllerApi
     */
    public submitNewWorkflow(submitRequestDto: SubmitRequestDto, options?: any) {
        return ProcessorControllerApiFp(this.configuration).submitNewWorkflow(submitRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

}


